2021-01-16T01:58:30-0300 [-] Creating router ...
2021-01-16T01:58:30-0300 [-] Initializing Router - Number of events: 1
2021-01-16T01:58:30-0300 [-] Initializing Server - Number of events: 2
2021-01-16T01:58:30-0300 [-] BrokerFactory starting on 5100
2021-01-16T01:58:30-0300 [-] Initializing Client - Number of events: 3
2021-01-16T01:58:30-0300 [-] Initializing sink node - Number of events: 4
2021-01-16T01:58:30-0300 [-] Initializing sink node - Number of events: 5
2021-01-16T01:58:31-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 45, in run
	    self.application.start(self.addr, self.port)
	  File "/home/rafael/iotfogsim/scinetsim/applications/pesquisaapp.py", line 27, in start
	    self.simulation_core.canvas.itemconfig(self.visual_component.draggable_name, text=str(addr+":"+str(port)))
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2581, in itemconfigure
	    return self._configure(('itemconfigure', tagOrId), cnf, kw)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 1479, in _configure
	    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:31-0300 [-] Initializing sensor node - Number of events: 6
2021-01-16T01:58:31-0300 [-] Initializing sensor node - Number of events: 7
2021-01-16T01:58:32-0300 [-] Initializing sensor node - Number of events: 8
2021-01-16T01:58:32-0300 [-] Initializing sensor node - Number of events: 9
2021-01-16T01:58:33-0300 [-] Initializing sensor node - Number of events: 10
2021-01-16T01:58:33-0300 [-] Initializing sensor node - Number of events: 11
2021-01-16T01:58:34-0300 [-] Initializing sensor node - Number of events: 12
2021-01-16T01:58:34-0300 [-] Initializing sensor node - Number of events: 13
2021-01-16T01:58:35-0300 [-] Initializing sensor node - Number of events: 14
2021-01-16T01:58:35-0300 [-] Initializing sensor node - Number of events: 15
2021-01-16T01:58:36-0300 [-] Initializing sensor node - Number of events: 16
2021-01-16T01:58:36-0300 [-] Initializing sensor node - Number of events: 17
2021-01-16T01:58:37-0300 [-] Initializing sensor node - Number of events: 18
2021-01-16T01:58:37-0300 [-] Initializing repeater node - Number of events: 19
2021-01-16T01:58:38-0300 [-] Initializing repeater node - Number of events: 20
2021-01-16T01:58:39-0300 [-] Initializing repeater node - Number of events: 21
2021-01-16T01:58:39-0300 [-] Initializing repeater node - Number of events: 22
2021-01-16T01:58:40-0300 [-] Initializing repeater node - Number of events: 23
2021-01-16T01:58:40-0300 [-] RouterFactory starting on 8081
2021-01-16T01:58:40-0300 [stdout#info] This divice have no simulation core instance
2021-01-16T01:58:40-0300 [stdout#info] This divice have no simulation core instance
2021-01-16T01:58:40-0300 [Uninitialized] 127.0.0.1:35402 - Connected to mqtt broker - Number of events: 24
2021-01-16T01:58:40-0300 [Uninitialized] 127.0.0.1:35402 - sending MQTT SUBSCRIBE REQUEST - Number of events: 25
2021-01-16T01:58:40-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7fde619cd710>
2021-01-16T01:58:41-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 316, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:41-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 316, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:41-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 249, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:41-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 249, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:41-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 249, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:41-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 249, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:41-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 249, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:41-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 249, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:41-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 249, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:41-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 249, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:42-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 249, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:42-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 249, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:42-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 249, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:42-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 249, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:42-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 249, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:42-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 284, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:42-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 284, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:42-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 284, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:42-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 284, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T01:58:42-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.6/threading.py", line 864, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 284, in run
	    nearby_devices_list = self.get_nearby_devices_list()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 139, in get_nearby_devices_list
	    nearby_devices_icon_list = self.find_nearby_devices_icon()
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 133, in find_nearby_devices_icon
	    self.visual_component.y-self.coverage_area_radius)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2548, in find_overlapping
	    return self.find('overlapping', x1, y1, x2, y2)
	  File "/usr/lib/python3.6/tkinter/__init__.py", line 2525, in find
	    self.tk.call((self._w, 'find') + args)) or ()
	builtins.RuntimeError: main thread is not in main loop
	
2021-01-16T02:02:39-0300 [-] Received SIGINT, shutting down.
2021-01-16T02:02:39-0300 [SCADAApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2021-01-16T02:02:39-0300 [SCADAApp,client] connection lost - Number of events: 26
2021-01-16T02:02:39-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2021-01-16T02:02:39-0300 [applications.pesquisaapp.BrokerFactory] (TCP Port 5100 Closed)
2021-01-16T02:02:39-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7fde619cd710>
2021-01-16T02:02:39-0300 [-] Main loop terminated.
