2021-01-19T23:50:37-0300 [-] Creating router ...
2021-01-19T23:50:37-0300 [-] Initializing Router - Number of events: 1
2021-01-19T23:50:37-0300 [-] Initializing Server - Number of events: 2
2021-01-19T23:50:37-0300 [-] Initializing Client - Number of events: 3
2021-01-19T23:50:37-0300 [-] Initializing sink node - Number of events: 4
2021-01-19T23:50:38-0300 [-] Initializing sensor node - Number of events: 5
2021-01-19T23:50:38-0300 [-] Initializing sensor node - Number of events: 6
2021-01-19T23:50:39-0300 [-] Initializing sensor node - Number of events: 7
2021-01-19T23:50:39-0300 [-] Initializing sensor node - Number of events: 8
2021-01-19T23:50:40-0300 [-] Initializing sensor node - Number of events: 9
2021-01-19T23:50:40-0300 [-] Initializing sensor node - Number of events: 10
2021-01-19T23:50:41-0300 [-] Initializing sensor node - Number of events: 11
2021-01-19T23:50:41-0300 [-] Initializing sensor node - Number of events: 12
2021-01-19T23:50:42-0300 [-] Initializing sensor node - Number of events: 13
2021-01-19T23:50:42-0300 [-] Initializing sensor node - Number of events: 14
2021-01-19T23:50:43-0300 [-] Initializing sensor node - Number of events: 15
2021-01-19T23:50:43-0300 [-] Initializing sensor node - Number of events: 16
2021-01-19T23:50:44-0300 [-] Initializing sensor node - Number of events: 17
2021-01-19T23:50:44-0300 [-] Initializing repeater node - Number of events: 18
2021-01-19T23:50:45-0300 [-] Initializing repeater node - Number of events: 19
2021-01-19T23:50:45-0300 [-] Initializing repeater node - Number of events: 20
2021-01-19T23:50:46-0300 [-] Initializing repeater node - Number of events: 21
2021-01-19T23:50:46-0300 [-] Initializing repeater node - Number of events: 22
2021-01-19T23:50:47-0300 [-] RouterFactory starting on 8081
2021-01-19T23:50:47-0300 [-] BrokerFactory starting on 5100
2021-01-19T23:50:47-0300 [stdout#info] This divice have no simulation core instance
2021-01-19T23:50:47-0300 [stdout#info] This divice have no simulation core instance
2021-01-19T23:50:47-0300 [Uninitialized] 127.0.0.1:43910 - Connected to mqtt broker - Number of events: 23
2021-01-19T23:50:47-0300 [Uninitialized] 127.0.0.1:43910 - sending MQTT SUBSCRIBE REQUEST - Number of events: 24
2021-01-19T23:50:47-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efe36613358>
2021-01-19T23:50:47-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 28, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 250, in run
	    self.application.start(nearby_devices_list)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 120, in start
	    self._propagate_signal()
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 63, in _propagate_signal
	    reactor.callAfter(0.1, self.set_signal_radius, radius=20)
	builtins.AttributeError: 'EPollReactor' object has no attribute 'callAfter'
	
2021-01-19T23:50:47-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 28, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 250, in run
	    self.application.start(nearby_devices_list)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 120, in start
	    self._propagate_signal()
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 63, in _propagate_signal
	    reactor.callAfter(0.1, self.set_signal_radius, radius=20)
	builtins.AttributeError: 'EPollReactor' object has no attribute 'callAfter'
	
2021-01-19T23:50:47-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 28, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 250, in run
	    self.application.start(nearby_devices_list)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 120, in start
	    self._propagate_signal()
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 63, in _propagate_signal
	    reactor.callAfter(0.1, self.set_signal_radius, radius=20)
	builtins.AttributeError: 'EPollReactor' object has no attribute 'callAfter'
	
2021-01-19T23:50:47-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 28, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 250, in run
	    self.application.start(nearby_devices_list)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 120, in start
	    self._propagate_signal()
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 63, in _propagate_signal
	    reactor.callAfter(0.1, self.set_signal_radius, radius=20)
	builtins.AttributeError: 'EPollReactor' object has no attribute 'callAfter'
	
2021-01-19T23:50:47-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 28, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 250, in run
	    self.application.start(nearby_devices_list)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 120, in start
	    self._propagate_signal()
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 63, in _propagate_signal
	    reactor.callAfter(0.1, self.set_signal_radius, radius=20)
	builtins.AttributeError: 'EPollReactor' object has no attribute 'callAfter'
	
2021-01-19T23:50:47-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 28, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 250, in run
	    self.application.start(nearby_devices_list)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 120, in start
	    self._propagate_signal()
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 63, in _propagate_signal
	    reactor.callAfter(0.1, self.set_signal_radius, radius=20)
	builtins.AttributeError: 'EPollReactor' object has no attribute 'callAfter'
	
2021-01-19T23:50:47-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 28, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 250, in run
	    self.application.start(nearby_devices_list)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 120, in start
	    self._propagate_signal()
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 63, in _propagate_signal
	    reactor.callAfter(0.1, self.set_signal_radius, radius=20)
	builtins.AttributeError: 'EPollReactor' object has no attribute 'callAfter'
	
2021-01-19T23:50:47-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 28, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 250, in run
	    self.application.start(nearby_devices_list)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 120, in start
	    self._propagate_signal()
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 63, in _propagate_signal
	    reactor.callAfter(0.1, self.set_signal_radius, radius=20)
	builtins.AttributeError: 'EPollReactor' object has no attribute 'callAfter'
	
2021-01-19T23:50:47-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 28, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 250, in run
	    self.application.start(nearby_devices_list)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 120, in start
	    self._propagate_signal()
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 63, in _propagate_signal
	    reactor.callAfter(0.1, self.set_signal_radius, radius=20)
	builtins.AttributeError: 'EPollReactor' object has no attribute 'callAfter'
	
2021-01-19T23:50:47-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 28, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 250, in run
	    self.application.start(nearby_devices_list)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 120, in start
	    self._propagate_signal()
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 63, in _propagate_signal
	    reactor.callAfter(0.1, self.set_signal_radius, radius=20)
	builtins.AttributeError: 'EPollReactor' object has no attribute 'callAfter'
	
2021-01-19T23:50:47-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 28, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 250, in run
	    self.application.start(nearby_devices_list)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 120, in start
	    self._propagate_signal()
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 63, in _propagate_signal
	    reactor.callAfter(0.1, self.set_signal_radius, radius=20)
	builtins.AttributeError: 'EPollReactor' object has no attribute 'callAfter'
	
2021-01-19T23:50:47-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 28, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 250, in run
	    self.application.start(nearby_devices_list)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 120, in start
	    self._propagate_signal()
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 63, in _propagate_signal
	    reactor.callAfter(0.1, self.set_signal_radius, radius=20)
	builtins.AttributeError: 'EPollReactor' object has no attribute 'callAfter'
	
2021-01-19T23:50:47-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 28, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 250, in run
	    self.application.start(nearby_devices_list)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 120, in start
	    self._propagate_signal()
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 63, in _propagate_signal
	    reactor.callAfter(0.1, self.set_signal_radius, radius=20)
	builtins.AttributeError: 'EPollReactor' object has no attribute 'callAfter'
	
2021-01-19T23:50:47-0300 [stdout#info] ========= wsn_repeater_1 ==========
2021-01-19T23:50:47-0300 [stdout#info] wsn_repeater_1  <------->  sensor_2
2021-01-19T23:50:47-0300 [stdout#info] wsn_repeater_1  <------->  wsn_repeater_2
2021-01-19T23:50:47-0300 [stdout#info] =============================
2021-01-19T23:50:47-0300 [stdout#info] ========= wsn_repeater_4 ==========
2021-01-19T23:50:47-0300 [stdout#info] wsn_repeater_4  <------->  sensor_11
2021-01-19T23:50:47-0300 [stdout#info] wsn_repeater_4  <------->  sensor_9
2021-01-19T23:50:47-0300 [stdout#info] wsn_repeater_4  <------->  wsn_repeater_5
2021-01-19T23:50:47-0300 [stdout#info] =============================
2021-01-19T23:50:47-0300 [stdout#info] ========= wsn_repeater_2 ==========
2021-01-19T23:50:47-0300 [stdout#info] wsn_repeater_2  <------->  wsn_repeater_1
2021-01-19T23:50:47-0300 [stdout#info] wsn_repeater_2  <------->  sensor_4
2021-01-19T23:50:47-0300 [stdout#info] wsn_repeater_2  <------->  wsn_repeater_3
2021-01-19T23:50:47-0300 [stdout#info] =============================
2021-01-19T23:50:47-0300 [stdout#info] ========= wsn_repeater_3 ==========
2021-01-19T23:50:47-0300 [stdout#info] wsn_repeater_3  <------->  wsn_repeater_2
2021-01-19T23:50:47-0300 [stdout#info] =============================
2021-01-19T23:50:47-0300 [stdout#info] ========= wsn_repeater_5 ==========
2021-01-19T23:50:47-0300 [stdout#info] wsn_repeater_5  <------->  wsn_repeater_4
2021-01-19T23:50:47-0300 [stdout#info] =============================
2021-01-19T23:50:47-0300 [stdout#info] This divice have no simulation core instance
2021-01-19T23:51:38-0300 [-] Received SIGINT, shutting down.
2021-01-19T23:51:38-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efe36613358>
2021-01-19T23:51:38-0300 [applications.pesquisaapp.BrokerFactory] (TCP Port 5100 Closed)
2021-01-19T23:51:38-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2021-01-19T23:51:38-0300 [SCADAApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2021-01-19T23:51:38-0300 [SCADAApp,client] connection lost - Number of events: 25
2021-01-19T23:51:38-0300 [-] Main loop terminated.
