2020-03-26T22:43:14-0300 [-] Creating router ...
2020-03-26T22:43:14-0300 [-] Initializing Router - Number of events: 1
2020-03-26T22:43:14-0300 [-] Creating AccessPoint station ...
2020-03-26T22:43:14-0300 [-] Initializing Access Point - Number of events: 2
2020-03-26T22:43:14-0300 [-] Access Point BEACON - Number of events: 3
2020-03-26T22:43:14-0300 [-] Creating fog node ...
2020-03-26T22:43:14-0300 [-] Initializing Client - Number of events: 4
2020-03-26T22:43:14-0300 [-] Creating fog node ...
2020-03-26T22:43:14-0300 [-] Initializing Server - Number of events: 5
2020-03-26T22:43:14-0300 [-] Creating iot node ...
2020-03-26T22:43:14-0300 [-] Initializing Client - Number of events: 6
2020-03-26T22:43:14-0300 [-] Creating iot node ...
2020-03-26T22:43:14-0300 [-] Initializing Client - Number of events: 7
2020-03-26T22:43:14-0300 [stderr#error] Exception in Tkinter callback
2020-03-26T22:43:14-0300 [stderr#error] Traceback (most recent call last):
2020-03-26T22:43:14-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-03-26T22:43:14-0300 [stderr#error]     return self.func(*args)
2020-03-26T22:43:14-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 101, in <lambda>
2020-03-26T22:43:14-0300 [stderr#error]     btn_open = ttk.Button(window, text="Open Project",command=lambda:open_project(window,simulation_core))
2020-03-26T22:43:14-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 55, in open_project
2020-03-26T22:43:14-0300 [stderr#error]     load_nodes(selected_project_name, simulation_core)
2020-03-26T22:43:14-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 198, in load_nodes
2020-03-26T22:43:14-0300 [stderr#error]     run_all_nodes(simulation_core)
2020-03-26T22:43:14-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 205, in run_all_nodes
2020-03-26T22:43:14-0300 [stderr#error]     print(routers[1])
2020-03-26T22:43:14-0300 [stderr#error] TypeError: 'dict_items' object does not support indexing
2020-03-26T22:43:14-0300 [-] Access Point BEACON - Number of events: 8
2020-03-26T22:43:15-0300 [-] Access Point BEACON - Number of events: 9
2020-03-26T22:43:15-0300 [-] Access Point BEACON - Number of events: 10
2020-03-26T22:43:15-0300 [-] Access Point BEACON - Number of events: 11
2020-03-26T22:43:15-0300 [-] Access Point BEACON - Number of events: 12
2020-03-26T22:43:15-0300 [-] Access Point BEACON - Number of events: 13
2020-03-26T22:43:15-0300 [-] Access Point BEACON - Number of events: 14
2020-03-26T22:43:15-0300 [-] Access Point BEACON - Number of events: 15
2020-03-26T22:43:15-0300 [-] Access Point BEACON - Number of events: 16
2020-03-26T22:43:15-0300 [-] Access Point BEACON - Number of events: 17
2020-03-26T22:43:16-0300 [-] Access Point BEACON - Number of events: 18
2020-03-26T22:43:16-0300 [-] Access Point BEACON - Number of events: 19
2020-03-26T22:43:16-0300 [-] Access Point BEACON - Number of events: 20
2020-03-26T22:43:16-0300 [-] Access Point BEACON - Number of events: 21
2020-03-26T22:43:16-0300 [-] Access Point BEACON - Number of events: 22
2020-03-26T22:43:16-0300 [-] Access Point BEACON - Number of events: 23
2020-03-26T22:43:16-0300 [-] Access Point BEACON - Number of events: 24
2020-03-26T22:43:16-0300 [-] Access Point BEACON - Number of events: 25
2020-03-26T22:43:16-0300 [-] Access Point BEACON - Number of events: 26
2020-03-26T22:43:17-0300 [-] Access Point BEACON - Number of events: 27
2020-03-26T22:43:17-0300 [-] Received SIGINT, shutting down.
2020-03-26T22:43:17-0300 [-] Main loop terminated.
