2020-04-14T23:16:09-0300 [-] Creating router ...
2020-04-14T23:16:09-0300 [stderr#error] Exception in Tkinter callback
2020-04-14T23:16:09-0300 [stderr#error] Traceback (most recent call last):
2020-04-14T23:16:09-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-04-14T23:16:09-0300 [stderr#error]     return self.func(*args)
2020-04-14T23:16:09-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 106, in <lambda>
2020-04-14T23:16:09-0300 [stderr#error]     btn_open = ttk.Button(window, text="Open Project",command=lambda:open_project(window,simulation_core))
2020-04-14T23:16:09-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 60, in open_project
2020-04-14T23:16:09-0300 [stderr#error]     load_nodes(selected_project_name, simulation_core)
2020-04-14T23:16:09-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 140, in load_nodes
2020-04-14T23:16:09-0300 [stderr#error]     rt = Router(simulation_core, router['port'], router['real_ip'], router['simulation_ip'], router['id'],router['name'], router['icon'], router['is_wireless'], router['x'], router['y'], router['application'], router['coverage_area_radius'])
2020-04-14T23:16:09-0300 [stderr#error] TypeError: __init__() takes 12 positional arguments but 13 were given
2020-04-14T23:18:07-0300 [-] Received SIGINT, shutting down.
2020-04-14T23:18:07-0300 [-] Main loop terminated.
