2020-02-25T10:20:23-0300 [-] Creating router ...
2020-02-25T10:20:23-0300 [-] Initializing Router - Number of events: 1
2020-02-25T10:20:23-0300 [-] ServerFactory starting on 8081
2020-02-25T10:20:23-0300 [-] Creating fog node ...
2020-02-25T10:20:23-0300 [stdout#info] applications.mqttapp.SubscriberApp
2020-02-25T10:20:23-0300 [-] Initializing Client - Number of events: 2
2020-02-25T10:20:23-0300 [-] Creating fog node ...
2020-02-25T10:20:23-0300 [-] Initializing Server - Number of events: 3
2020-02-25T10:20:23-0300 [-] BrokerFactory starting on 5100
2020-02-25T10:20:23-0300 [-] Creating iot node ...
2020-02-25T10:20:23-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-25T10:20:23-0300 [-] Initializing Client - Number of events: 4
2020-02-25T10:20:23-0300 [-] Creating iot node ...
2020-02-25T10:20:23-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-25T10:20:23-0300 [-] Initializing Client - Number of events: 5
2020-02-25T10:20:23-0300 [Uninitialized] 127.0.0.1:40060 - Connected to mqtt broker - Number of events: 6
2020-02-25T10:20:23-0300 [Uninitialized] 127.0.0.1:40060 - sending MQTT SUBSCRIBE REQUEST - Number of events: 7
2020-02-25T10:20:23-0300 [Uninitialized] 127.0.0.1:40062 - Connected to mqtt broker - Number of events: 8
2020-02-25T10:20:23-0300 [Uninitialized] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 9
2020-02-25T10:20:23-0300 [Uninitialized] 127.0.0.1:40064 - Connected to mqtt broker - Number of events: 10
2020-02-25T10:20:23-0300 [Uninitialized] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 11
2020-02-25T10:20:28-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 12
2020-02-25T10:20:28-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 13
2020-02-25T10:20:33-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 14
2020-02-25T10:20:33-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 15
2020-02-25T10:20:38-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 16
2020-02-25T10:20:38-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 17
2020-02-25T10:20:43-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 18
2020-02-25T10:20:43-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 19
2020-02-25T10:20:48-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 20
2020-02-25T10:20:48-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 21
2020-02-25T10:20:53-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 22
2020-02-25T10:20:53-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 23
2020-02-25T10:20:58-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 24
2020-02-25T10:20:58-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 25
2020-02-25T10:21:03-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 26
2020-02-25T10:21:03-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 27
2020-02-25T10:21:08-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 28
2020-02-25T10:21:08-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 29
2020-02-25T10:21:13-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 30
2020-02-25T10:21:13-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 31
2020-02-25T10:21:18-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 32
2020-02-25T10:21:18-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 33
2020-02-25T10:21:23-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 34
2020-02-25T10:21:23-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 35
2020-02-25T10:21:28-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 36
2020-02-25T10:21:28-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 37
2020-02-25T10:21:33-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 38
2020-02-25T10:21:33-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 39
2020-02-25T10:21:38-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 40
2020-02-25T10:21:38-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 41
2020-02-25T10:21:43-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 42
2020-02-25T10:21:43-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 43
2020-02-25T10:21:48-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 44
2020-02-25T10:21:48-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 45
2020-02-25T10:21:53-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 46
2020-02-25T10:21:53-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 47
2020-02-25T10:21:58-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 48
2020-02-25T10:21:58-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 49
2020-02-25T10:22:03-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 50
2020-02-25T10:22:03-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 51
2020-02-25T10:22:08-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 52
2020-02-25T10:22:08-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 53
2020-02-25T10:22:13-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 54
2020-02-25T10:22:13-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 55
2020-02-25T10:22:18-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 56
2020-02-25T10:22:18-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 57
2020-02-25T10:22:23-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 58
2020-02-25T10:22:23-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 59
2020-02-25T10:22:28-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 60
2020-02-25T10:22:28-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 61
2020-02-25T10:22:33-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 62
2020-02-25T10:22:33-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 63
2020-02-25T10:22:38-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 64
2020-02-25T10:22:38-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 65
2020-02-25T10:22:43-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 66
2020-02-25T10:22:43-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 67
2020-02-25T10:22:48-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 68
2020-02-25T10:22:48-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 69
2020-02-25T10:22:53-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 70
2020-02-25T10:22:53-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 71
2020-02-25T10:22:58-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 72
2020-02-25T10:22:58-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 73
2020-02-25T10:23:03-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 74
2020-02-25T10:23:03-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 75
2020-02-25T10:23:08-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 76
2020-02-25T10:23:08-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 77
2020-02-25T10:23:13-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 78
2020-02-25T10:23:13-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 79
2020-02-25T10:23:18-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 80
2020-02-25T10:23:18-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 81
2020-02-25T10:23:23-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 82
2020-02-25T10:23:23-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 83
2020-02-25T10:23:28-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 84
2020-02-25T10:23:28-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 85
2020-02-25T10:23:33-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 86
2020-02-25T10:23:33-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 87
2020-02-25T10:23:38-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 88
2020-02-25T10:23:38-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 89
2020-02-25T10:23:43-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 90
2020-02-25T10:23:43-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 91
2020-02-25T10:23:48-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 92
2020-02-25T10:23:48-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 93
2020-02-25T10:23:53-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 94
2020-02-25T10:23:53-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 95
2020-02-25T10:23:58-0300 [-] 127.0.0.1:40062 - sending MQTT PUBLISH REQUEST - Number of events: 96
2020-02-25T10:23:58-0300 [-] 127.0.0.1:40064 - sending MQTT PUBLISH REQUEST - Number of events: 97
2020-02-25T10:23:59-0300 [-] Received SIGINT, shutting down.
2020-02-25T10:23:59-0300 [BrokerProtocol,9,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145069e0f0>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,74,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d064e0>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,11,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145069e470>
	
2020-02-25T10:23:59-0300 [twisted.internet.protocol.ServerFactory] (TCP Port 8081 Closed)
2020-02-25T10:23:59-0300 [BrokerProtocol,86,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d0e400>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,71,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d061d0>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,83,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d0e1d0>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,10,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145069e198>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,72,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d06160>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,84,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d0e320>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,73,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d064a8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,15,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145069e828>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,75,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d062b0>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,14,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145069e6a0>
	
2020-02-25T10:23:59-0300 [RouterApp,1,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-25T10:23:59-0300 [RouterApp,1,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 58, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-25T10:23:59-0300 [RouterApp,0,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-25T10:23:59-0300 [RouterApp,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 58, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-25T10:23:59-0300 [BrokerProtocol,87,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d0e518>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,85,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d0e4e0>
	
2020-02-25T10:23:59-0300 [RouterApp,2,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-25T10:23:59-0300 [RouterApp,2,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 58, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-25T10:23:59-0300 [BrokerProtocol,13,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145069e630>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,79,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d06550>
	
2020-02-25T10:23:59-0300 [applications.mqttapp.BrokerFactory] (TCP Port 5100 Closed)
2020-02-25T10:23:59-0300 [BrokerProtocol,12,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145069e5c0>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,16,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145069ea20>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,77,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d069b0>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,88,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d0e390>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,76,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d067f0>
	
2020-02-25T10:23:59-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-25T10:23:59-0300 [PublisherApp,client] connection lost - Number of events: 98
2020-02-25T10:23:59-0300 [BrokerProtocol,78,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d06748>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,17,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145069ec50>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,19,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145069eda0>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,80,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d06dd8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,81,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d06b00>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,18,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145069ecc0>
	
2020-02-25T10:23:59-0300 [SubscriberApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-25T10:23:59-0300 [SubscriberApp,client] connection lost - Number of events: 99
2020-02-25T10:23:59-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-25T10:23:59-0300 [PublisherApp,client] connection lost - Number of events: 100
2020-02-25T10:23:59-0300 [BrokerProtocol,20,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145069ef60>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,82,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d06c88>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,22,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d25240>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,59,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451cfd198>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,36,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d350f0>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,21,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d25208>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,23,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d25400>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,48,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451ce3048>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,27,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d256a0>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,61,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451cfd358>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,54,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451ce3240>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,38,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d353c8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,49,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451ce3400>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,60,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451cfd2b0>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,1,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145068d400>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,2,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145068d390>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,24,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d252e8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,37,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d35400>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,62,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451cfd5f8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,50,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451ce3390>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,26,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145068d550>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,63,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451cfd550>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,5,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145068db70>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,28,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d25588>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,39,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d356d8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,67,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451cfdb70>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,51,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451ce3630>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,25,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d25438>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,40,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d35438>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,64,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451cfd860>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,3,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145068d748>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,30,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d25828>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,42,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d351d0>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,52,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451ce36d8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,53,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451ce37b8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,65,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451cfd6a0>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,4,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145068d940>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,41,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d35908>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,55,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451ce3b38>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,29,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d25940>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,68,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451cfdcf8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,31,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d25ba8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,43,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d35ba8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,66,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451cfd080>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,35,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d35198>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,32,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d25a90>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,6,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145068dc50>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,34,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d25dd8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,44,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d359b0>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,56,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451ce3860>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,45,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d35e48>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,57,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451ce3cf8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,7,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145068ddd8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,46,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d35f60>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,58,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451ce3fd0>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,33,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451d25e10>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,47,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451ce30b8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,8,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f145068df60>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,69,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451cfd9e8>
	
2020-02-25T10:23:59-0300 [BrokerProtocol,70,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.destiny_port = self.transport.getPeer().port
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f1451cfdb00>
	
2020-02-25T10:23:59-0300 [-] Main loop terminated.
