2020-02-25T10:33:52-0300 [-] Creating router ...
2020-02-25T10:33:52-0300 [-] Initializing Router - Number of events: 1
2020-02-25T10:33:52-0300 [-] ServerFactory starting on 8081
2020-02-25T10:33:52-0300 [-] Creating fog node ...
2020-02-25T10:33:52-0300 [stdout#info] applications.mqttapp.SubscriberApp
2020-02-25T10:33:52-0300 [-] Initializing Client - Number of events: 2
2020-02-25T10:33:52-0300 [-] Creating fog node ...
2020-02-25T10:33:52-0300 [-] Initializing Server - Number of events: 3
2020-02-25T10:33:52-0300 [-] BrokerFactory starting on 5100
2020-02-25T10:33:52-0300 [-] Creating iot node ...
2020-02-25T10:33:52-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-25T10:33:52-0300 [-] Initializing Client - Number of events: 4
2020-02-25T10:33:52-0300 [-] Creating iot node ...
2020-02-25T10:33:52-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-25T10:33:52-0300 [-] Initializing Client - Number of events: 5
2020-02-25T10:33:52-0300 [stdout#info] {<applications.mqttapp.SubscriberApp object at 0x7f2ed6909668>}
2020-02-25T10:33:52-0300 [Uninitialized] 127.0.0.1:40830 - Connected to mqtt broker - Number of events: 6
2020-02-25T10:33:52-0300 [Uninitialized] 127.0.0.1:40830 - sending MQTT SUBSCRIBE REQUEST - Number of events: 7
2020-02-25T10:33:52-0300 [stdout#info] {<applications.mqttapp.PublisherApp object at 0x7f2ecf4d9a20>, <applications.mqttapp.SubscriberApp object at 0x7f2ed6909668>}
2020-02-25T10:33:52-0300 [Uninitialized] 127.0.0.1:40832 - Connected to mqtt broker - Number of events: 8
2020-02-25T10:33:52-0300 [Uninitialized] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 9
2020-02-25T10:33:52-0300 [stdout#info] {<applications.mqttapp.PublisherApp object at 0x7f2ecf4d9e10>, <applications.mqttapp.PublisherApp object at 0x7f2ecf4d9a20>, <applications.mqttapp.SubscriberApp object at 0x7f2ed6909668>}
2020-02-25T10:33:52-0300 [Uninitialized] 127.0.0.1:40834 - Connected to mqtt broker - Number of events: 10
2020-02-25T10:33:52-0300 [Uninitialized] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 11
2020-02-25T10:33:52-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:33:52-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:33:52-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:33:57-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 12
2020-02-25T10:33:57-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 13
2020-02-25T10:33:57-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:33:57-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:02-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 14
2020-02-25T10:34:02-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 15
2020-02-25T10:34:02-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:02-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:07-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 16
2020-02-25T10:34:07-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 17
2020-02-25T10:34:07-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:07-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:12-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 18
2020-02-25T10:34:12-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 19
2020-02-25T10:34:12-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:12-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:17-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 20
2020-02-25T10:34:17-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 21
2020-02-25T10:34:17-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:17-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:22-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 22
2020-02-25T10:34:22-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 23
2020-02-25T10:34:22-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:22-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:27-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 24
2020-02-25T10:34:27-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 25
2020-02-25T10:34:27-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:27-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:32-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 26
2020-02-25T10:34:32-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:32-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 27
2020-02-25T10:34:32-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:37-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 28
2020-02-25T10:34:37-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:37-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 29
2020-02-25T10:34:37-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:42-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 30
2020-02-25T10:34:42-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:42-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 31
2020-02-25T10:34:42-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:47-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 32
2020-02-25T10:34:47-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 33
2020-02-25T10:34:47-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:47-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:52-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 34
2020-02-25T10:34:52-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:52-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 35
2020-02-25T10:34:52-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:57-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 36
2020-02-25T10:34:57-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:34:57-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 37
2020-02-25T10:34:57-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:02-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 38
2020-02-25T10:35:02-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:02-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 39
2020-02-25T10:35:02-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:07-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 40
2020-02-25T10:35:07-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:07-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 41
2020-02-25T10:35:07-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:12-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 42
2020-02-25T10:35:12-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:12-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 43
2020-02-25T10:35:12-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:17-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 44
2020-02-25T10:35:17-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:17-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 45
2020-02-25T10:35:17-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:22-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 46
2020-02-25T10:35:22-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:22-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 47
2020-02-25T10:35:22-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:27-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 48
2020-02-25T10:35:27-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:27-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 49
2020-02-25T10:35:27-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:32-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 50
2020-02-25T10:35:32-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:32-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 51
2020-02-25T10:35:32-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:37-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 52
2020-02-25T10:35:37-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:37-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 53
2020-02-25T10:35:37-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:42-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 54
2020-02-25T10:35:42-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:42-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 55
2020-02-25T10:35:42-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:47-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 56
2020-02-25T10:35:47-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:47-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 57
2020-02-25T10:35:47-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:52-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 58
2020-02-25T10:35:52-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:52-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 59
2020-02-25T10:35:52-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:57-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 60
2020-02-25T10:35:57-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:35:57-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 61
2020-02-25T10:35:57-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:36:02-0300 [-] 127.0.0.1:40832 - sending MQTT PUBLISH REQUEST - Number of events: 62
2020-02-25T10:36:02-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:36:02-0300 [-] 127.0.0.1:40834 - sending MQTT PUBLISH REQUEST - Number of events: 63
2020-02-25T10:36:02-0300 [applications.mqttapp.BrokerFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 154, in connectionMade
	    if self.simulation_core:
	builtins.AttributeError: 'BrokerProtocol' object has no attribute 'simulation_core'
	
2020-02-25T10:36:06-0300 [-] Received SIGINT, shutting down.
2020-02-25T10:36:06-0300 [BrokerProtocol,31,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b5c080>
	
2020-02-25T10:36:06-0300 [twisted.internet.protocol.ServerFactory] (TCP Port 8081 Closed)
2020-02-25T10:36:06-0300 [BrokerProtocol,6,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b3e2b0>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,34,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b5c198>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,20,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b4b3c8>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,44,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b770f0>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,32,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b5c2b0>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,18,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b4b320>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,5,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b3e1d0>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,43,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b77080>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,47,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b77748>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,17,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b4b208>
	
2020-02-25T10:36:06-0300 [RouterApp,1,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-25T10:36:06-0300 [RouterApp,1,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 58, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-25T10:36:06-0300 [BrokerProtocol,45,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b775c0>
	
2020-02-25T10:36:06-0300 [RouterApp,0,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-25T10:36:06-0300 [RouterApp,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 58, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-25T10:36:06-0300 [BrokerProtocol,15,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b3edd8>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,7,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b3e240>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,27,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b3eb38>
	
2020-02-25T10:36:06-0300 [RouterApp,2,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-25T10:36:06-0300 [RouterApp,2,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 58, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-25T10:36:06-0300 [BrokerProtocol,8,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b3e400>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,23,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b4b400>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,33,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b5c5c0>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,19,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b4b550>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,9,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b3e5c0>
	
2020-02-25T10:36:06-0300 [applications.mqttapp.BrokerFactory] (TCP Port 5100 Closed)
2020-02-25T10:36:06-0300 [BrokerProtocol,21,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b4b780>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,46,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b77470>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,10,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b3e7f0>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,36,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b5c7b8>
	
2020-02-25T10:36:06-0300 [SubscriberApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-25T10:36:06-0300 [SubscriberApp,client] connection lost - Number of events: 64
2020-02-25T10:36:06-0300 [BrokerProtocol,22,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b4b828>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,40,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b5cf60>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,35,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b5c748>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,48,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b777b8>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,12,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b3ea58>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,13,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b3ecf8>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,54,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b77f60>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,38,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b5ca20>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,30,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b4bfd0>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,24,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b4b978>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,49,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b779b0>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,11,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b3e8d0>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,37,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b5ca90>
	
2020-02-25T10:36:06-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-25T10:36:06-0300 [PublisherApp,client] connection lost - Number of events: 65
2020-02-25T10:36:06-0300 [BrokerProtocol,50,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b77b70>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,1,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ecf4edbe0>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,28,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b4b940>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,41,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b5ceb8>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,2,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ecf4edc18>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,14,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b3eda0>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,39,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b5ccf8>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,25,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b4bda0>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,4,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ecf4edf60>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,51,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b77550>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,3,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ecf4edcf8>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,26,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b4bc18>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,52,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b77a20>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,16,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b3ed30>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,29,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b4bf60>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,53,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b77588>
	
2020-02-25T10:36:06-0300 [BrokerProtocol,42,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 169, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f2ed0b5cfd0>
	
2020-02-25T10:36:06-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-25T10:36:06-0300 [PublisherApp,client] connection lost - Number of events: 66
2020-02-25T10:36:06-0300 [-] Main loop terminated.
