2020-02-26T10:09:59-0300 [-] Creating router ...
2020-02-26T10:10:00-0300 [-] Initializing Router - Number of events: 1
2020-02-26T10:10:00-0300 [-] RouterFactory starting on 8081
2020-02-26T10:10:00-0300 [-] Creating fog node ...
2020-02-26T10:10:00-0300 [stdout#info] applications.mqttapp.SubscriberApp
2020-02-26T10:10:00-0300 [-] Initializing Client - Number of events: 2
2020-02-26T10:10:00-0300 [-] Creating fog node ...
2020-02-26T10:10:00-0300 [-] Initializing Server - Number of events: 3
2020-02-26T10:10:00-0300 [-] BrokerFactory starting on 5100
2020-02-26T10:10:00-0300 [-] Creating iot node ...
2020-02-26T10:10:00-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-26T10:10:00-0300 [-] Initializing Client - Number of events: 4
2020-02-26T10:10:00-0300 [-] Creating iot node ...
2020-02-26T10:10:00-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-26T10:10:00-0300 [-] Initializing Client - Number of events: 5
2020-02-26T10:10:00-0300 [stdout#info] This divice have no simulation core instance
2020-02-26T10:10:00-0300 [stdout#info] This divice have no simulation core instance
2020-02-26T10:10:00-0300 [stdout#info] This divice have no simulation core instance
2020-02-26T10:10:00-0300 [stdout#info] This divice have no simulation core instance
2020-02-26T10:10:00-0300 [Uninitialized] 127.0.0.1:51574 - Connected to mqtt broker - Number of events: 6
2020-02-26T10:10:00-0300 [Uninitialized] 127.0.0.1:51574 - sending MQTT SUBSCRIBE REQUEST - Number of events: 7
2020-02-26T10:10:00-0300 [Uninitialized] 127.0.0.1:51576 - Connected to mqtt broker - Number of events: 8
2020-02-26T10:10:00-0300 [Uninitialized] 127.0.0.1:51576 - sending MQTT PUBLISH REQUEST - Number of events: 9
2020-02-26T10:10:00-0300 [Uninitialized] 127.0.0.1:51578 - Connected to mqtt broker - Number of events: 10
2020-02-26T10:10:00-0300 [Uninitialized] 127.0.0.1:51578 - sending MQTT PUBLISH REQUEST - Number of events: 11
2020-02-26T10:10:00-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff78eb5eb70>
2020-02-26T10:10:00-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff78eb5ed68>
2020-02-26T10:10:00-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff78eb5ef60>
2020-02-26T10:10:00-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 124, in connectionMade
	    self._wrappedProtocol.makeConnection(self.transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 130, in connectionMade
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:10:00-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff78eb5eb70>
2020-02-26T10:10:00-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 124, in connectionMade
	    self._wrappedProtocol.makeConnection(self.transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 130, in connectionMade
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:10:00-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff78eb5ed68>
2020-02-26T10:10:00-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 124, in connectionMade
	    self._wrappedProtocol.makeConnection(self.transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 130, in connectionMade
	    self.simulation_core.allProtocols.remove(self)
	builtins.KeyError: <applications.routerapp.ClientProtocol object at 0x7ff78eb5ed30>
	
2020-02-26T10:10:00-0300 [Uninitialized] connection lost: <applications.routerapp.ClientProtocol object at 0x7ff78eb5ed30>
2020-02-26T10:10:00-0300 [Uninitialized] connection lost - Number of events: 12
2020-02-26T10:10:00-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff78eb5ef60>
2020-02-26T10:10:00-0300 [BrokerProtocol,0,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:10:00-0300 [BrokerProtocol,1,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:10:00-0300 [BrokerProtocol,2,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:10:05-0300 [-] 127.0.0.1:51576 - sending MQTT PUBLISH REQUEST - Number of events: 13
2020-02-26T10:10:05-0300 [-] 127.0.0.1:51578 - sending MQTT PUBLISH REQUEST - Number of events: 14
2020-02-26T10:10:05-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901ec1d0>
2020-02-26T10:10:05-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901ec3c8>
2020-02-26T10:10:05-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 124, in connectionMade
	    self._wrappedProtocol.makeConnection(self.transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 130, in connectionMade
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:10:05-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901ec1d0>
2020-02-26T10:10:05-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 124, in connectionMade
	    self._wrappedProtocol.makeConnection(self.transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 130, in connectionMade
	    self.simulation_core.allProtocols.remove(self)
	builtins.KeyError: <applications.routerapp.ClientProtocol object at 0x7ff7901ec198>
	
2020-02-26T10:10:05-0300 [Uninitialized] connection lost: <applications.routerapp.ClientProtocol object at 0x7ff7901ec198>
2020-02-26T10:10:05-0300 [Uninitialized] connection lost - Number of events: 15
2020-02-26T10:10:05-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901ec3c8>
2020-02-26T10:10:05-0300 [BrokerProtocol,3,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:10:05-0300 [BrokerProtocol,4,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:10:10-0300 [-] 127.0.0.1:51576 - sending MQTT PUBLISH REQUEST - Number of events: 16
2020-02-26T10:10:10-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901ec7b8>
2020-02-26T10:10:10-0300 [-] 127.0.0.1:51578 - sending MQTT PUBLISH REQUEST - Number of events: 17
2020-02-26T10:10:10-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 124, in connectionMade
	    self._wrappedProtocol.makeConnection(self.transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 130, in connectionMade
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:10:10-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901ec7b8>
2020-02-26T10:10:10-0300 [BrokerProtocol,5,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:10:10-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901eca90>
2020-02-26T10:10:10-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 124, in connectionMade
	    self._wrappedProtocol.makeConnection(self.transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 130, in connectionMade
	    self.simulation_core.allProtocols.remove(self)
	builtins.KeyError: <applications.routerapp.ClientProtocol object at 0x7ff7901ec978>
	
2020-02-26T10:10:10-0300 [Uninitialized] connection lost: <applications.routerapp.ClientProtocol object at 0x7ff7901ec978>
2020-02-26T10:10:10-0300 [Uninitialized] connection lost - Number of events: 18
2020-02-26T10:10:10-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901eca90>
2020-02-26T10:10:10-0300 [BrokerProtocol,6,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:10:15-0300 [-] 127.0.0.1:51576 - sending MQTT PUBLISH REQUEST - Number of events: 19
2020-02-26T10:10:15-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901ecda0>
2020-02-26T10:10:15-0300 [-] 127.0.0.1:51578 - sending MQTT PUBLISH REQUEST - Number of events: 20
2020-02-26T10:10:15-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 124, in connectionMade
	    self._wrappedProtocol.makeConnection(self.transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 130, in connectionMade
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:10:15-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901ecda0>
2020-02-26T10:10:15-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff79017b0b8>
2020-02-26T10:10:15-0300 [BrokerProtocol,7,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:10:15-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 124, in connectionMade
	    self._wrappedProtocol.makeConnection(self.transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 130, in connectionMade
	    self.simulation_core.allProtocols.remove(self)
	builtins.KeyError: <applications.routerapp.ClientProtocol object at 0x7ff7901eca58>
	
2020-02-26T10:10:15-0300 [Uninitialized] connection lost: <applications.routerapp.ClientProtocol object at 0x7ff7901eca58>
2020-02-26T10:10:15-0300 [Uninitialized] connection lost - Number of events: 21
2020-02-26T10:10:15-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff79017b0b8>
2020-02-26T10:10:15-0300 [BrokerProtocol,8,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:10:20-0300 [-] 127.0.0.1:51576 - sending MQTT PUBLISH REQUEST - Number of events: 22
2020-02-26T10:10:20-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff79017b400>
2020-02-26T10:10:20-0300 [-] 127.0.0.1:51578 - sending MQTT PUBLISH REQUEST - Number of events: 23
2020-02-26T10:10:20-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 124, in connectionMade
	    self._wrappedProtocol.makeConnection(self.transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 130, in connectionMade
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:10:20-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff79017b400>
2020-02-26T10:10:20-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901ecb70>
2020-02-26T10:10:20-0300 [BrokerProtocol,9,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:10:20-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 124, in connectionMade
	    self._wrappedProtocol.makeConnection(self.transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 130, in connectionMade
	    self.simulation_core.allProtocols.remove(self)
	builtins.KeyError: <applications.routerapp.ClientProtocol object at 0x7ff7901ecd68>
	
2020-02-26T10:10:20-0300 [Uninitialized] connection lost: <applications.routerapp.ClientProtocol object at 0x7ff7901ecd68>
2020-02-26T10:10:20-0300 [Uninitialized] connection lost - Number of events: 24
2020-02-26T10:10:20-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901ecb70>
2020-02-26T10:10:20-0300 [BrokerProtocol,10,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:10:25-0300 [-] 127.0.0.1:51576 - sending MQTT PUBLISH REQUEST - Number of events: 25
2020-02-26T10:10:25-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901ec860>
2020-02-26T10:10:25-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 124, in connectionMade
	    self._wrappedProtocol.makeConnection(self.transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 130, in connectionMade
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:10:25-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901ec860>
2020-02-26T10:10:25-0300 [-] 127.0.0.1:51578 - sending MQTT PUBLISH REQUEST - Number of events: 26
2020-02-26T10:10:25-0300 [BrokerProtocol,11,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:10:25-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901ec470>
2020-02-26T10:10:25-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 124, in connectionMade
	    self._wrappedProtocol.makeConnection(self.transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 130, in connectionMade
	    self.simulation_core.allProtocols.remove(self)
	builtins.KeyError: <applications.routerapp.ClientProtocol object at 0x7ff7901ecda0>
	
2020-02-26T10:10:25-0300 [Uninitialized] connection lost: <applications.routerapp.ClientProtocol object at 0x7ff7901ecda0>
2020-02-26T10:10:25-0300 [Uninitialized] connection lost - Number of events: 27
2020-02-26T10:10:25-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7ff7901ec470>
2020-02-26T10:10:25-0300 [BrokerProtocol,12,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:10:27-0300 [-] Received SIGINT, shutting down.
2020-02-26T10:10:27-0300 [applications.mqttapp.BrokerFactory] (TCP Port 5100 Closed)
2020-02-26T10:10:27-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-02-26T10:10:27-0300 [SubscriberApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-26T10:10:27-0300 [SubscriberApp,client] connection lost - Number of events: 28
2020-02-26T10:10:27-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-26T10:10:27-0300 [PublisherApp,client] connection lost - Number of events: 29
2020-02-26T10:10:27-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-26T10:10:27-0300 [PublisherApp,client] connection lost - Number of events: 30
2020-02-26T10:10:27-0300 [RouterAppProtocol,3,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-26T10:10:27-0300 [RouterAppProtocol,3,127.0.0.1] connection lost - Number of events: 31
2020-02-26T10:10:27-0300 [-] Main loop terminated.
