2020-02-25T16:40:22-0300 [-] Creating router ...
2020-02-25T16:40:22-0300 [-] Initializing Router - Number of events: 1
2020-02-25T16:40:22-0300 [-] RouterFactory starting on 8081
2020-02-25T16:40:22-0300 [stdout#info] None
2020-02-25T16:40:22-0300 [-] Creating fog node ...
2020-02-25T16:40:22-0300 [stdout#info] applications.mqttapp.SubscriberApp
2020-02-25T16:40:22-0300 [-] Initializing Client - Number of events: 2
2020-02-25T16:40:22-0300 [-] Creating fog node ...
2020-02-25T16:40:22-0300 [-] Initializing Server - Number of events: 3
2020-02-25T16:40:22-0300 [-] BrokerFactory starting on 5100
2020-02-25T16:40:22-0300 [-] Creating iot node ...
2020-02-25T16:40:22-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-25T16:40:22-0300 [-] Initializing Client - Number of events: 4
2020-02-25T16:40:22-0300 [-] Creating iot node ...
2020-02-25T16:40:22-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-25T16:40:22-0300 [-] Initializing Client - Number of events: 5
2020-02-25T16:40:22-0300 [Uninitialized] 127.0.0.1:45238 - Connected to mqtt broker - Number of events: 6
2020-02-25T16:40:22-0300 [Uninitialized] 127.0.0.1:45238 - sending MQTT SUBSCRIBE REQUEST - Number of events: 7
2020-02-25T16:40:22-0300 [stdout#info] {<applications.mqttapp.SubscriberApp object at 0x7f06b21c0b38>}
2020-02-25T16:40:22-0300 [Uninitialized] 127.0.0.1:45240 - Connected to mqtt broker - Number of events: 8
2020-02-25T16:40:22-0300 [Uninitialized] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 9
2020-02-25T16:40:22-0300 [stdout#info] {<applications.mqttapp.PublisherApp object at 0x7f06aad8fda0>, <applications.mqttapp.SubscriberApp object at 0x7f06b21c0b38>}
2020-02-25T16:40:22-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 124, in connectionMade
	    self._wrappedProtocol.makeConnection(self.transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 50, in connectionMade
	    self.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 78, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 227, in create_connection
	    x2 = self.device2.visual_component.x
	builtins.AttributeError: 'NoneType' object has no attribute 'visual_component'
	
2020-02-25T16:40:22-0300 [Uninitialized] connection lost: 'NoneType' object has no attribute 'visual_component'
2020-02-25T16:40:22-0300 [Uninitialized] connection lost - Number of events: 10
2020-02-25T16:40:22-0300 [Uninitialized] 127.0.0.1:45242 - Connected to mqtt broker - Number of events: 11
2020-02-25T16:40:22-0300 [Uninitialized] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 12
2020-02-25T16:40:22-0300 [stdout#info] {<applications.mqttapp.PublisherApp object at 0x7f06aad8fda0>, <applications.mqttapp.SubscriberApp object at 0x7f06b21c0b38>, <applications.mqttapp.PublisherApp object at 0x7f06aad9f1d0>}
2020-02-25T16:40:22-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 124, in connectionMade
	    self._wrappedProtocol.makeConnection(self.transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 50, in connectionMade
	    self.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 78, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 215, in __init__
	    self.device2 = simulation_core.get_any_protocol_by_addr_and_port(destiny_addr, destiny_port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/simulationcore.py", line 29, in get_any_protocol_by_addr_and_port
	    if proto.transport.getHost().host == addr and proto.transport.getHost().port == port:
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 759, in getHost
	    return self._addressType('TCP', *_getsockname(self.socket))
	builtins.AttributeError: 'Client' object has no attribute 'socket'
	
2020-02-25T16:40:22-0300 [Uninitialized] connection lost: 'Client' object has no attribute 'socket'
2020-02-25T16:40:22-0300 [Uninitialized] connection lost - Number of events: 13
2020-02-25T16:40:22-0300 [RouterAppProtocol,1,127.0.0.1] connection lost: Connection was closed cleanly.
2020-02-25T16:40:22-0300 [RouterAppProtocol,1,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 23, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1295, in mainLoop
	    self.doIteration(t)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/epollreactor.py", line 235, in doPoll
	    log.callWithLogger(selectable, _drdw, selectable, fd, event)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 627, in _doReadOrWrite
	    self._disconnectSelectable(selectable, why, inRead)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 252, in _disconnectSelectable
	    selectable.readConnectionLost(f)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 307, in readConnectionLost
	    self.connectionLost(reason)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 55, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-25T16:40:22-0300 [RouterAppProtocol,2,127.0.0.1] connection lost: Connection was closed cleanly.
2020-02-25T16:40:22-0300 [RouterAppProtocol,2,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 23, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1295, in mainLoop
	    self.doIteration(t)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/epollreactor.py", line 235, in doPoll
	    log.callWithLogger(selectable, _drdw, selectable, fd, event)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 627, in _doReadOrWrite
	    self._disconnectSelectable(selectable, why, inRead)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 252, in _disconnectSelectable
	    selectable.readConnectionLost(f)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 307, in readConnectionLost
	    self.connectionLost(reason)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 55, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-25T16:40:22-0300 [stdout#info] {<applications.mqttapp.PublisherApp object at 0x7f06aad8fda0>, <applications.mqttapp.SubscriberApp object at 0x7f06b21c0b38>, <applications.mqttapp.PublisherApp object at 0x7f06aad9f1d0>, <applications.mqttapp.BrokerProtocol object at 0x7f06aad9f470>}
2020-02-25T16:40:27-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 14
2020-02-25T16:40:27-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 15
2020-02-25T16:40:32-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 16
2020-02-25T16:40:32-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 17
2020-02-25T16:40:37-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 18
2020-02-25T16:40:37-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 19
2020-02-25T16:40:42-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 20
2020-02-25T16:40:42-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 21
2020-02-25T16:40:47-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 22
2020-02-25T16:40:47-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 23
2020-02-25T16:40:52-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 24
2020-02-25T16:40:52-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 25
2020-02-25T16:40:57-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 26
2020-02-25T16:40:57-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 27
2020-02-25T16:41:02-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 28
2020-02-25T16:41:02-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 29
2020-02-25T16:41:07-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 30
2020-02-25T16:41:07-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 31
2020-02-25T16:41:12-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 32
2020-02-25T16:41:12-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 33
2020-02-25T16:41:17-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 34
2020-02-25T16:41:17-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 35
2020-02-25T16:41:22-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 36
2020-02-25T16:41:22-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 37
2020-02-25T16:41:27-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 38
2020-02-25T16:41:27-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 39
2020-02-25T16:41:32-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 40
2020-02-25T16:41:32-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 41
2020-02-25T16:41:37-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 42
2020-02-25T16:41:37-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 43
2020-02-25T16:41:42-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 44
2020-02-25T16:41:42-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 45
2020-02-25T16:41:47-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 46
2020-02-25T16:41:47-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 47
2020-02-25T16:41:52-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 48
2020-02-25T16:41:52-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 49
2020-02-25T16:41:57-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 50
2020-02-25T16:41:57-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 51
2020-02-25T16:42:02-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 52
2020-02-25T16:42:02-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 53
2020-02-25T16:42:07-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 54
2020-02-25T16:42:07-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 55
2020-02-25T16:42:12-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 56
2020-02-25T16:42:12-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 57
2020-02-25T16:42:17-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 58
2020-02-25T16:42:17-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 59
2020-02-25T16:42:22-0300 [-] 127.0.0.1:45240 - sending MQTT PUBLISH REQUEST - Number of events: 60
2020-02-25T16:42:22-0300 [-] 127.0.0.1:45242 - sending MQTT PUBLISH REQUEST - Number of events: 61
2020-02-25T16:42:24-0300 [-] Received SIGINT, shutting down.
2020-02-25T16:42:24-0300 [applications.mqttapp.BrokerFactory] (TCP Port 5100 Closed)
2020-02-25T16:42:24-0300 [SubscriberApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-25T16:42:24-0300 [SubscriberApp,client] connection lost - Number of events: 62
2020-02-25T16:42:24-0300 [RouterAppProtocol,0,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-25T16:42:24-0300 [RouterAppProtocol,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 55, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-25T16:42:24-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-02-25T16:42:24-0300 [-] Main loop terminated.
