2020-06-06T22:50:10-0300 [-] Creating router ...
2020-06-06T22:50:10-0300 [-] Initializing Router - Number of events: 1
2020-06-06T22:50:10-0300 [-] RouterFactory starting on 8081
2020-06-06T22:50:10-0300 [-] Creating AccessPoint station ...
2020-06-06T22:50:10-0300 [-] Initializing Access Point - Number of events: 2
2020-06-06T22:50:11-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:11-0300 [stdout#info] não dado na saida
2020-06-06T22:50:11-0300 [-] Initializing Server - Number of events: 3
2020-06-06T22:50:11-0300 [-] HttpServerAppFactory starting on 8082
2020-06-06T22:50:11-0300 [-] Initializing sensor node - Number of events: 4
2020-06-06T22:50:12-0300 [stdout#info] Not connected to a wireless access point
2020-06-06T22:50:12-0300 [stdout#info] Assossiated to : notebook 1
2020-06-06T22:50:12-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:12-0300 [stdout#info] não dado na saida
2020-06-06T22:50:12-0300 [stdout#info] This divice have no simulation core instance
2020-06-06T22:50:12-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-06-06T22:50:12-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/task.py", line 239, in __call__
	    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
	    result = f(*args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wirelesscomputerapp.py", line 39, in main_app
	    self.send(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wirelesscomputerapp.py", line 53, in send
	    self.associated_ap._buffer_in.add(package)
	builtins.AttributeError: 'AccessPointApp' object has no attribute '_buffer_in'
	
2020-06-06T22:50:13-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:13-0300 [stdout#info] não dado na saida
2020-06-06T22:50:14-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:14-0300 [stdout#info] não dado na saida
2020-06-06T22:50:15-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:15-0300 [stdout#info] não dado na saida
2020-06-06T22:50:16-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:16-0300 [stdout#info] não dado na saida
2020-06-06T22:50:17-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:17-0300 [stdout#info] não dado na saida
2020-06-06T22:50:18-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:18-0300 [stdout#info] não dado na saida
2020-06-06T22:50:19-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:19-0300 [stdout#info] não dado na saida
2020-06-06T22:50:20-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:20-0300 [stdout#info] não dado na saida
2020-06-06T22:50:21-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:21-0300 [stdout#info] não dado na saida
2020-06-06T22:50:22-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:22-0300 [stdout#info] não dado na saida
2020-06-06T22:50:23-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:23-0300 [stdout#info] não dado na saida
2020-06-06T22:50:24-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:24-0300 [stdout#info] não dado na saida
2020-06-06T22:50:25-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:25-0300 [stdout#info] não dado na saida
2020-06-06T22:50:26-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:26-0300 [stdout#info] não dado na saida
2020-06-06T22:50:27-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:27-0300 [stdout#info] não dado na saida
2020-06-06T22:50:28-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:28-0300 [stdout#info] não dado na saida
2020-06-06T22:50:29-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:29-0300 [stdout#info] não dado na saida
2020-06-06T22:50:30-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:30-0300 [stdout#info] não dado na saida
2020-06-06T22:50:31-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:31-0300 [stdout#info] não dado na saida
2020-06-06T22:50:32-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:32-0300 [stdout#info] não dado na saida
2020-06-06T22:50:33-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:33-0300 [stdout#info] não dado na saida
2020-06-06T22:50:34-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:34-0300 [stdout#info] não dado na saida
2020-06-06T22:50:35-0300 [stdout#info] Não tem dado na entrada
2020-06-06T22:50:35-0300 [stdout#info] não dado na saida
2020-06-06T22:50:36-0300 [-] Received SIGINT, shutting down.
2020-06-06T22:50:36-0300 [applications.httpapp.HttpServerAppFactory] (TCP Port 8082 Closed)
2020-06-06T22:50:36-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-06-06T22:50:36-0300 [-] Main loop terminated.
