2020-06-07T12:32:01-0300 [-] Initializing Server - Number of events: 1
2020-06-07T12:32:01-0300 [-] HttpServerAppFactory starting on 8080
2020-06-07T12:32:01-0300 [-] Creating router ...
2020-06-07T12:32:01-0300 [-] Initializing Router - Number of events: 2
2020-06-07T12:32:02-0300 [-] RouterFactory starting on 8081
2020-06-07T12:32:02-0300 [-] Creating AccessPoint station ...
2020-06-07T12:32:02-0300 [-] Initializing Access Point - Number of events: 3
2020-06-07T12:32:02-0300 [stderr#error] Exception in Tkinter callback
2020-06-07T12:32:02-0300 [stderr#error] Traceback (most recent call last):
2020-06-07T12:32:02-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-06-07T12:32:02-0300 [stderr#error]     return self.func(*args)
2020-06-07T12:32:02-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 107, in <lambda>
2020-06-07T12:32:02-0300 [stderr#error]     btn_open = ttk.Button(window, text="Open Project",command=lambda:open_project(window,simulation_core))
2020-06-07T12:32:02-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 61, in open_project
2020-06-07T12:32:02-0300 [stderr#error]     load_nodes(selected_project_name, simulation_core)
2020-06-07T12:32:02-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 161, in load_nodes
2020-06-07T12:32:02-0300 [stderr#error]     ap.run()
2020-06-07T12:32:02-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 320, in run
2020-06-07T12:32:02-0300 [stderr#error]     self.application.start()
2020-06-07T12:32:02-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/accesspointapp.py", line 76, in start
2020-06-07T12:32:02-0300 [stderr#error]     self.connect_to_gateway()
2020-06-07T12:32:02-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/accesspointapp.py", line 251, in connect_to_gateway
2020-06-07T12:32:02-0300 [stderr#error]     d.addCallback(save_protocol)
2020-06-07T12:32:02-0300 [stderr#error] AttributeError: 'Connector' object has no attribute 'addCallback'
2020-06-07T12:32:03-0300 [stdout#info] This divice have no simulation core instance
2020-06-07T12:32:03-0300 [stdout#info] This divice have no simulation core instance
2020-06-07T12:32:03-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/accesspointapp.py", line 26, in connectionMade
	    self.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 107, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 156, in __init__
	    self.device2 = simulation_core.get_any_protocol_by_addr_and_port(destiny_addr, destiny_port)
	builtins.AttributeError: 'NoneType' object has no attribute 'get_any_protocol_by_addr_and_port'
	
2020-06-07T12:38:57-0300 [-] Received SIGINT, shutting down.
2020-06-07T12:38:57-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-06-07T12:38:57-0300 [applications.httpapp.HttpServerAppFactory] (TCP Port 8080 Closed)
2020-06-07T12:38:57-0300 [-] Main loop terminated.
