2020-06-07T13:50:07-0300 [-] Creating router ...
2020-06-07T13:50:07-0300 [-] Initializing Router - Number of events: 1
2020-06-07T13:50:07-0300 [-] RouterFactory starting on 8081
2020-06-07T13:50:07-0300 [-] Creating AccessPoint station ...
2020-06-07T13:50:07-0300 [-] Initializing Access Point - Number of events: 2
2020-06-07T13:50:08-0300 [-] Initializing Server - Number of events: 3
2020-06-07T13:50:08-0300 [-] HttpServerAppFactory starting on 8080
2020-06-07T13:50:08-0300 [-] Initializing sensor node - Number of events: 4
2020-06-07T13:50:09-0300 [stdout#info] Not connected to a wireless access point
2020-06-07T13:50:09-0300 [stdout#info] Assossiated to : notebook 1
2020-06-07T13:50:09-0300 [stdout#info] This divice have no simulation core instance
2020-06-07T13:50:09-0300 [applications.routerapp.RouterFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 119, in connectionMade
	    self.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 107, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 156, in __init__
	    self.device2 = simulation_core.get_any_protocol_by_addr_and_port(destiny_addr, destiny_port)
	builtins.AttributeError: 'NoneType' object has no attribute 'get_any_protocol_by_addr_and_port'
	
2020-06-07T13:50:09-0300 [stdout#info] This divice have no simulation core instance
2020-06-07T13:50:09-0300 [applications.routerapp.RouterFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
	    protocol.makeConnection(transport)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 119, in connectionMade
	    self.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 107, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 156, in __init__
	    self.device2 = simulation_core.get_any_protocol_by_addr_and_port(destiny_addr, destiny_port)
	builtins.AttributeError: 'NoneType' object has no attribute 'get_any_protocol_by_addr_and_port'
	
2020-06-07T13:50:10-0300 [stdout#info] {b'{"destiny_addr": "127.0.0.1", "destiny_port": 8080, "source_addr": "127.0.0.1", "source_port": 8888, "type": "http", "payload": "HTTP 1.0 / GET request"}'}
2020-06-07T13:50:10-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f7f777cf3c8>
2020-06-07T13:50:10-0300 [applications.httpapp.HttpServerAppFactory] Connection received - Number of events: 5
2020-06-07T13:50:10-0300 [HttpServerAppProtocol,0,127.0.0.1] Received from client HTTP 1.0 / GET request
2020-06-07T13:50:10-0300 [HttpServerAppProtocol,0,127.0.0.1] Sending HTTP RESPONSE - Number of events: 6
2020-06-07T13:51:08-0300 [-] Received SIGINT, shutting down.
2020-06-07T13:51:08-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f7f777cf3c8>
2020-06-07T13:51:08-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-06-07T13:51:08-0300 [HttpServerAppProtocol,0,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-06-07T13:51:08-0300 [HttpServerAppProtocol,0,127.0.0.1] connection lost - Number of events: 7
2020-06-07T13:51:08-0300 [applications.httpapp.HttpServerAppFactory] (TCP Port 8080 Closed)
2020-06-07T13:51:08-0300 [-] Main loop terminated.
