2020-02-24T13:27:26-0300 [-] Creating router ...
2020-02-24T13:27:26-0300 [-] Initializing Router - Number of events: 1
2020-02-24T13:27:26-0300 [-] ServerFactory starting on 8081
2020-02-24T13:27:26-0300 [-] Creating AccessPoint station ...
2020-02-24T13:27:26-0300 [-] Initializing Access Point - Number of events: 2
2020-02-24T13:27:26-0300 [-] Access Point BEACON - Number of events: 3
2020-02-24T13:27:26-0300 [-] Creating fog node ...
2020-02-24T13:27:26-0300 [stdout#info] applications.mqttapp.SubscriberApp
2020-02-24T13:27:26-0300 [-] Initializing Client - Number of events: 4
2020-02-24T13:27:26-0300 [-] Creating fog node ...
2020-02-24T13:27:26-0300 [-] Initializing Server - Number of events: 5
2020-02-24T13:27:26-0300 [-] BrokerFactory starting on 5100
2020-02-24T13:27:26-0300 [-] Creating iot node ...
2020-02-24T13:27:26-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-24T13:27:26-0300 [-] Initializing Client - Number of events: 6
2020-02-24T13:27:26-0300 [-] Creating iot node ...
2020-02-24T13:27:26-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-24T13:27:26-0300 [-] Initializing Client - Number of events: 7
2020-02-24T13:27:26-0300 [-] Creating iot node ...
2020-02-24T13:27:26-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-24T13:27:26-0300 [-] Initializing Client - Number of events: 8
2020-02-24T13:27:26-0300 [-] Creating iot node ...
2020-02-24T13:27:26-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-24T13:27:26-0300 [-] Initializing Client - Number of events: 9
2020-02-24T13:27:26-0300 [-] Creating iot node ...
2020-02-24T13:27:26-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-24T13:27:26-0300 [-] Initializing Client - Number of events: 10
2020-02-24T13:27:26-0300 [-] Creating iot node ...
2020-02-24T13:27:26-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-24T13:27:26-0300 [-] Initializing Client - Number of events: 11
2020-02-24T13:27:26-0300 [Uninitialized] 127.0.0.1:55996 - Connected to mqtt broker - Number of events: 12
2020-02-24T13:27:26-0300 [Uninitialized] 127.0.0.1:55996 - sending MQTT SUBSCRIBE REQUEST - Number of events: 13
2020-02-24T13:27:26-0300 [Uninitialized] 127.0.0.1:55998 - Connected to mqtt broker - Number of events: 14
2020-02-24T13:27:26-0300 [Uninitialized] 127.0.0.1:55998 - sending MQTT PUBLISH REQUEST - Number of events: 15
2020-02-24T13:27:26-0300 [Uninitialized] 127.0.0.1:56000 - Connected to mqtt broker - Number of events: 16
2020-02-24T13:27:26-0300 [Uninitialized] 127.0.0.1:56000 - sending MQTT PUBLISH REQUEST - Number of events: 17
2020-02-24T13:27:26-0300 [Uninitialized] 127.0.0.1:56002 - Connected to mqtt broker - Number of events: 18
2020-02-24T13:27:26-0300 [Uninitialized] 127.0.0.1:56002 - sending MQTT PUBLISH REQUEST - Number of events: 19
2020-02-24T13:27:26-0300 [Uninitialized] 127.0.0.1:56004 - Connected to mqtt broker - Number of events: 20
2020-02-24T13:27:26-0300 [Uninitialized] 127.0.0.1:56004 - sending MQTT PUBLISH REQUEST - Number of events: 21
2020-02-24T13:27:26-0300 [Uninitialized] 127.0.0.1:56006 - Connected to mqtt broker - Number of events: 22
2020-02-24T13:27:26-0300 [Uninitialized] 127.0.0.1:56006 - sending MQTT PUBLISH REQUEST - Number of events: 23
2020-02-24T13:27:26-0300 [Uninitialized] 127.0.0.1:56008 - Connected to mqtt broker - Number of events: 24
2020-02-24T13:27:26-0300 [Uninitialized] 127.0.0.1:56008 - sending MQTT PUBLISH REQUEST - Number of events: 25
2020-02-24T13:27:26-0300 [-] Access Point BEACON - Number of events: 26
2020-02-24T13:27:26-0300 [-] Access Point BEACON - Number of events: 27
2020-02-24T13:27:26-0300 [-] Access Point BEACON - Number of events: 28
2020-02-24T13:27:26-0300 [-] Access Point BEACON - Number of events: 29
2020-02-24T13:27:27-0300 [-] Access Point BEACON - Number of events: 30
2020-02-24T13:27:27-0300 [-] Access Point BEACON - Number of events: 31
2020-02-24T13:27:27-0300 [-] Access Point BEACON - Number of events: 32
2020-02-24T13:27:27-0300 [-] Access Point BEACON - Number of events: 33
2020-02-24T13:27:27-0300 [-] Access Point BEACON - Number of events: 34
2020-02-24T13:27:27-0300 [-] Access Point BEACON - Number of events: 35
2020-02-24T13:27:27-0300 [-] Access Point BEACON - Number of events: 36
2020-02-24T13:27:27-0300 [-] Access Point BEACON - Number of events: 37
2020-02-24T13:27:27-0300 [-] Access Point BEACON - Number of events: 38
2020-02-24T13:27:28-0300 [-] Access Point BEACON - Number of events: 39
2020-02-24T13:27:28-0300 [-] Access Point BEACON - Number of events: 40
2020-02-24T13:27:28-0300 [-] Access Point BEACON - Number of events: 41
2020-02-24T13:27:28-0300 [-] Access Point BEACON - Number of events: 42
2020-02-24T13:27:28-0300 [-] Access Point BEACON - Number of events: 43
2020-02-24T13:27:28-0300 [-] Access Point BEACON - Number of events: 44
2020-02-24T13:27:28-0300 [-] Access Point BEACON - Number of events: 45
2020-02-24T13:27:28-0300 [-] Access Point BEACON - Number of events: 46
2020-02-24T13:27:28-0300 [-] Access Point BEACON - Number of events: 47
2020-02-24T13:27:29-0300 [-] Access Point BEACON - Number of events: 48
2020-02-24T13:27:29-0300 [-] Access Point BEACON - Number of events: 49
2020-02-24T13:27:29-0300 [-] Access Point BEACON - Number of events: 50
2020-02-24T13:27:29-0300 [-] Access Point BEACON - Number of events: 51
2020-02-24T13:27:29-0300 [-] Access Point BEACON - Number of events: 52
2020-02-24T13:27:29-0300 [-] Access Point BEACON - Number of events: 53
2020-02-24T13:27:29-0300 [-] Access Point BEACON - Number of events: 54
2020-02-24T13:27:29-0300 [-] Access Point BEACON - Number of events: 55
2020-02-24T13:27:29-0300 [-] Access Point BEACON - Number of events: 56
2020-02-24T13:27:30-0300 [-] Access Point BEACON - Number of events: 57
2020-02-24T13:27:30-0300 [-] Access Point BEACON - Number of events: 58
2020-02-24T13:27:30-0300 [-] Access Point BEACON - Number of events: 59
2020-02-24T13:27:30-0300 [-] Access Point BEACON - Number of events: 60
2020-02-24T13:27:30-0300 [-] Access Point BEACON - Number of events: 61
2020-02-24T13:27:30-0300 [-] Access Point BEACON - Number of events: 62
2020-02-24T13:27:30-0300 [-] Access Point BEACON - Number of events: 63
2020-02-24T13:27:30-0300 [-] Access Point BEACON - Number of events: 64
2020-02-24T13:27:30-0300 [-] Access Point BEACON - Number of events: 65
2020-02-24T13:27:31-0300 [-] Access Point BEACON - Number of events: 66
2020-02-24T13:27:31-0300 [-] Access Point BEACON - Number of events: 67
2020-02-24T13:27:31-0300 [-] Access Point BEACON - Number of events: 68
2020-02-24T13:27:31-0300 [-] Access Point BEACON - Number of events: 69
2020-02-24T13:27:31-0300 [-] Access Point BEACON - Number of events: 70
2020-02-24T13:27:31-0300 [-] 127.0.0.1:55998 - sending MQTT PUBLISH REQUEST - Number of events: 71
2020-02-24T13:27:31-0300 [-] 127.0.0.1:56000 - sending MQTT PUBLISH REQUEST - Number of events: 72
2020-02-24T13:27:31-0300 [-] 127.0.0.1:56002 - sending MQTT PUBLISH REQUEST - Number of events: 73
2020-02-24T13:27:31-0300 [-] 127.0.0.1:56004 - sending MQTT PUBLISH REQUEST - Number of events: 74
2020-02-24T13:27:31-0300 [-] 127.0.0.1:56006 - sending MQTT PUBLISH REQUEST - Number of events: 75
2020-02-24T13:27:31-0300 [-] 127.0.0.1:56008 - sending MQTT PUBLISH REQUEST - Number of events: 76
2020-02-24T13:27:31-0300 [-] Access Point BEACON - Number of events: 77
2020-02-24T13:27:31-0300 [-] Access Point BEACON - Number of events: 78
2020-02-24T13:27:31-0300 [-] Access Point BEACON - Number of events: 79
2020-02-24T13:27:31-0300 [-] Access Point BEACON - Number of events: 80
2020-02-24T13:27:32-0300 [-] Access Point BEACON - Number of events: 81
2020-02-24T13:27:32-0300 [-] Access Point BEACON - Number of events: 82
2020-02-24T13:27:32-0300 [-] Access Point BEACON - Number of events: 83
2020-02-24T13:27:32-0300 [-] Access Point BEACON - Number of events: 84
2020-02-24T13:27:32-0300 [-] Access Point BEACON - Number of events: 85
2020-02-24T13:27:32-0300 [-] Access Point BEACON - Number of events: 86
2020-02-24T13:27:32-0300 [-] Access Point BEACON - Number of events: 87
2020-02-24T13:27:32-0300 [-] Access Point BEACON - Number of events: 88
2020-02-24T13:27:32-0300 [-] Access Point BEACON - Number of events: 89
2020-02-24T13:27:33-0300 [-] Access Point BEACON - Number of events: 90
2020-02-24T13:27:33-0300 [-] Access Point BEACON - Number of events: 91
2020-02-24T13:27:33-0300 [-] Access Point BEACON - Number of events: 92
2020-02-24T13:27:33-0300 [-] Access Point BEACON - Number of events: 93
2020-02-24T13:27:33-0300 [-] Access Point BEACON - Number of events: 94
2020-02-24T13:27:33-0300 [-] Access Point BEACON - Number of events: 95
2020-02-24T13:27:33-0300 [-] Access Point BEACON - Number of events: 96
2020-02-24T13:27:33-0300 [-] Access Point BEACON - Number of events: 97
2020-02-24T13:27:33-0300 [-] Access Point BEACON - Number of events: 98
2020-02-24T13:27:34-0300 [-] Access Point BEACON - Number of events: 99
2020-02-24T13:27:34-0300 [-] Access Point BEACON - Number of events: 100
2020-02-24T13:27:34-0300 [-] Access Point BEACON - Number of events: 101
2020-02-24T13:27:34-0300 [-] Access Point BEACON - Number of events: 102
2020-02-24T13:27:34-0300 [-] Access Point BEACON - Number of events: 103
2020-02-24T13:27:34-0300 [-] Access Point BEACON - Number of events: 104
2020-02-24T13:27:34-0300 [-] Access Point BEACON - Number of events: 105
2020-02-24T13:27:34-0300 [-] Access Point BEACON - Number of events: 106
2020-02-24T13:27:34-0300 [-] Access Point BEACON - Number of events: 107
2020-02-24T13:27:35-0300 [-] Access Point BEACON - Number of events: 108
2020-02-24T13:27:35-0300 [-] Access Point BEACON - Number of events: 109
2020-02-24T13:27:35-0300 [-] Access Point BEACON - Number of events: 110
2020-02-24T13:27:35-0300 [-] Access Point BEACON - Number of events: 111
2020-02-24T13:27:35-0300 [-] Access Point BEACON - Number of events: 112
2020-02-24T13:27:35-0300 [-] Access Point BEACON - Number of events: 113
2020-02-24T13:27:35-0300 [-] Access Point BEACON - Number of events: 114
2020-02-24T13:27:35-0300 [-] Access Point BEACON - Number of events: 115
2020-02-24T13:27:35-0300 [-] Access Point BEACON - Number of events: 116
2020-02-24T13:27:36-0300 [-] Access Point BEACON - Number of events: 117
2020-02-24T13:27:36-0300 [-] Access Point BEACON - Number of events: 118
2020-02-24T13:27:36-0300 [-] Access Point BEACON - Number of events: 119
2020-02-24T13:27:36-0300 [-] Access Point BEACON - Number of events: 120
2020-02-24T13:27:36-0300 [-] Access Point BEACON - Number of events: 121
2020-02-24T13:27:36-0300 [-] 127.0.0.1:55998 - sending MQTT PUBLISH REQUEST - Number of events: 122
2020-02-24T13:27:36-0300 [-] 127.0.0.1:56000 - sending MQTT PUBLISH REQUEST - Number of events: 123
2020-02-24T13:27:36-0300 [-] 127.0.0.1:56002 - sending MQTT PUBLISH REQUEST - Number of events: 124
2020-02-24T13:27:36-0300 [-] 127.0.0.1:56004 - sending MQTT PUBLISH REQUEST - Number of events: 125
2020-02-24T13:27:36-0300 [-] 127.0.0.1:56006 - sending MQTT PUBLISH REQUEST - Number of events: 126
2020-02-24T13:27:36-0300 [-] 127.0.0.1:56008 - sending MQTT PUBLISH REQUEST - Number of events: 127
2020-02-24T13:27:36-0300 [-] Access Point BEACON - Number of events: 128
2020-02-24T13:27:36-0300 [-] Access Point BEACON - Number of events: 129
2020-02-24T13:27:36-0300 [-] Access Point BEACON - Number of events: 130
2020-02-24T13:27:36-0300 [-] Access Point BEACON - Number of events: 131
2020-02-24T13:27:37-0300 [-] Access Point BEACON - Number of events: 132
2020-02-24T13:27:37-0300 [-] Access Point BEACON - Number of events: 133
2020-02-24T13:27:37-0300 [-] Access Point BEACON - Number of events: 134
2020-02-24T13:27:37-0300 [-] Access Point BEACON - Number of events: 135
2020-02-24T13:27:37-0300 [-] Access Point BEACON - Number of events: 136
2020-02-24T13:27:37-0300 [-] Access Point BEACON - Number of events: 137
2020-02-24T13:27:37-0300 [-] Access Point BEACON - Number of events: 138
2020-02-24T13:27:37-0300 [-] Access Point BEACON - Number of events: 139
2020-02-24T13:27:37-0300 [-] Access Point BEACON - Number of events: 140
2020-02-24T13:27:38-0300 [-] Access Point BEACON - Number of events: 141
2020-02-24T13:27:38-0300 [-] Access Point BEACON - Number of events: 142
2020-02-24T13:27:38-0300 [-] Access Point BEACON - Number of events: 143
2020-02-24T13:27:38-0300 [-] Access Point BEACON - Number of events: 144
2020-02-24T13:27:38-0300 [-] Access Point BEACON - Number of events: 145
2020-02-24T13:27:38-0300 [-] Access Point BEACON - Number of events: 146
2020-02-24T13:27:38-0300 [-] Access Point BEACON - Number of events: 147
2020-02-24T13:27:38-0300 [-] Access Point BEACON - Number of events: 148
2020-02-24T13:27:38-0300 [-] Access Point BEACON - Number of events: 149
2020-02-24T13:27:39-0300 [-] Access Point BEACON - Number of events: 150
2020-02-24T13:27:39-0300 [-] Access Point BEACON - Number of events: 151
2020-02-24T13:27:39-0300 [-] Access Point BEACON - Number of events: 152
2020-02-24T13:27:39-0300 [-] Access Point BEACON - Number of events: 153
2020-02-24T13:27:39-0300 [-] Access Point BEACON - Number of events: 154
2020-02-24T13:27:39-0300 [-] Access Point BEACON - Number of events: 155
2020-02-24T13:27:39-0300 [-] Access Point BEACON - Number of events: 156
2020-02-24T13:27:39-0300 [-] Access Point BEACON - Number of events: 157
2020-02-24T13:27:39-0300 [-] Access Point BEACON - Number of events: 158
2020-02-24T13:27:40-0300 [-] Access Point BEACON - Number of events: 159
2020-02-24T13:27:40-0300 [-] Access Point BEACON - Number of events: 160
2020-02-24T13:27:40-0300 [-] Access Point BEACON - Number of events: 161
2020-02-24T13:27:40-0300 [-] Access Point BEACON - Number of events: 162
2020-02-24T13:27:40-0300 [-] Access Point BEACON - Number of events: 163
2020-02-24T13:27:40-0300 [-] Access Point BEACON - Number of events: 164
2020-02-24T13:27:40-0300 [-] Access Point BEACON - Number of events: 165
2020-02-24T13:27:40-0300 [-] Access Point BEACON - Number of events: 166
2020-02-24T13:27:40-0300 [-] Access Point BEACON - Number of events: 167
2020-02-24T13:27:41-0300 [-] Access Point BEACON - Number of events: 168
2020-02-24T13:27:41-0300 [-] Access Point BEACON - Number of events: 169
2020-02-24T13:27:41-0300 [-] Access Point BEACON - Number of events: 170
2020-02-24T13:27:41-0300 [-] Access Point BEACON - Number of events: 171
2020-02-24T13:27:41-0300 [-] Access Point BEACON - Number of events: 172
2020-02-24T13:27:41-0300 [-] Access Point BEACON - Number of events: 173
2020-02-24T13:27:41-0300 [-] 127.0.0.1:55998 - sending MQTT PUBLISH REQUEST - Number of events: 174
2020-02-24T13:27:41-0300 [-] 127.0.0.1:56000 - sending MQTT PUBLISH REQUEST - Number of events: 175
2020-02-24T13:27:41-0300 [-] 127.0.0.1:56002 - sending MQTT PUBLISH REQUEST - Number of events: 176
2020-02-24T13:27:41-0300 [-] 127.0.0.1:56004 - sending MQTT PUBLISH REQUEST - Number of events: 177
2020-02-24T13:27:41-0300 [-] 127.0.0.1:56006 - sending MQTT PUBLISH REQUEST - Number of events: 178
2020-02-24T13:27:41-0300 [-] 127.0.0.1:56008 - sending MQTT PUBLISH REQUEST - Number of events: 179
2020-02-24T13:27:41-0300 [-] Access Point BEACON - Number of events: 180
2020-02-24T13:27:41-0300 [-] Access Point BEACON - Number of events: 181
2020-02-24T13:27:41-0300 [-] Access Point BEACON - Number of events: 182
2020-02-24T13:27:41-0300 [-] Received SIGINT, shutting down.
2020-02-24T13:27:41-0300 [SubscriberApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-24T13:27:41-0300 [SubscriberApp,client] connection lost - Number of events: 183
2020-02-24T13:27:41-0300 [twisted.internet.protocol.ServerFactory] (TCP Port 8081 Closed)
2020-02-24T13:27:41-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-24T13:27:41-0300 [PublisherApp,client] connection lost - Number of events: 184
2020-02-24T13:27:41-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-24T13:27:41-0300 [PublisherApp,client] connection lost - Number of events: 185
2020-02-24T13:27:41-0300 [RouterApp,0,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-24T13:27:41-0300 [RouterApp,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 52, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-24T13:27:41-0300 [BrokerProtocol,19,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f8239a972e8>
	
2020-02-24T13:27:41-0300 [RouterApp,2,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-24T13:27:41-0300 [RouterApp,2,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 52, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-24T13:27:41-0300 [BrokerProtocol,21,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f8239a97160>
	
2020-02-24T13:27:41-0300 [RouterApp,3,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-24T13:27:41-0300 [RouterApp,3,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 52, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-24T13:27:41-0300 [BrokerProtocol,20,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f8239a97438>
	
2020-02-24T13:27:41-0300 [BrokerProtocol,9,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f823840c5c0>
	
2020-02-24T13:27:41-0300 [RouterApp,4,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-24T13:27:41-0300 [RouterApp,4,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 52, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-24T13:27:41-0300 [RouterApp,5,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-24T13:27:41-0300 [RouterApp,5,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 52, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-24T13:27:41-0300 [RouterApp,6,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-24T13:27:41-0300 [RouterApp,6,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 52, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-24T13:27:41-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-24T13:27:41-0300 [PublisherApp,client] connection lost - Number of events: 186
2020-02-24T13:27:41-0300 [BrokerProtocol,7,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f823840c3c8>
	
2020-02-24T13:27:41-0300 [BrokerProtocol,11,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f823840c908>
	
2020-02-24T13:27:41-0300 [BrokerProtocol,8,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f823840c6d8>
	
2020-02-24T13:27:41-0300 [BrokerProtocol,22,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f8239a97908>
	
2020-02-24T13:27:41-0300 [BrokerProtocol,10,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f823840c7b8>
	
2020-02-24T13:27:41-0300 [applications.mqttapp.BrokerFactory] (TCP Port 5100 Closed)
2020-02-24T13:27:42-0300 [BrokerProtocol,23,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f8239a97a20>
	
2020-02-24T13:27:42-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-24T13:27:42-0300 [PublisherApp,client] connection lost - Number of events: 187
2020-02-24T13:27:42-0300 [BrokerProtocol,12,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f823840c9e8>
	
2020-02-24T13:27:42-0300 [BrokerProtocol,2,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f82383fbc18>
	
2020-02-24T13:27:42-0300 [BrokerProtocol,24,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f8239a97ac8>
	
2020-02-24T13:27:42-0300 [BrokerProtocol,1,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f82383fbba8>
	
2020-02-24T13:27:42-0300 [BrokerProtocol,15,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f823840cac8>
	
2020-02-24T13:27:42-0300 [BrokerProtocol,16,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f823840cf98>
	
2020-02-24T13:27:42-0300 [BrokerProtocol,3,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f82383fb978>
	
2020-02-24T13:27:42-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-24T13:27:42-0300 [PublisherApp,client] connection lost - Number of events: 188
2020-02-24T13:27:42-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-24T13:27:42-0300 [PublisherApp,client] connection lost - Number of events: 189
2020-02-24T13:27:42-0300 [BrokerProtocol,4,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f82383fbcc0>
	
2020-02-24T13:27:42-0300 [BrokerProtocol,13,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f823840c160>
	
2020-02-24T13:27:42-0300 [BrokerProtocol,5,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f82383fbd30>
	
2020-02-24T13:27:42-0300 [BrokerProtocol,6,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f82383fbda0>
	
2020-02-24T13:27:42-0300 [BrokerProtocol,14,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f823840cef0>
	
2020-02-24T13:27:42-0300 [RouterApp,1,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-24T13:27:42-0300 [RouterApp,1,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 52, in connectionLost
	    self.simulation_core.updateEventsCounter("connection lost")
	builtins.AttributeError: 'NoneType' object has no attribute 'updateEventsCounter'
	
2020-02-24T13:27:42-0300 [BrokerProtocol,17,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f823840cdd8>
	
2020-02-24T13:27:42-0300 [BrokerProtocol,18,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 706, in disconnectAll
	    failure.Failure(main.CONNECTION_LOST))
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 151, in connectionLost
	    self.factory.subscribers.remove(self)
	builtins.KeyError: <applications.mqttapp.BrokerProtocol object at 0x7f8239a97048>
	
2020-02-24T13:27:42-0300 [-] Main loop terminated.
