2020-05-21T08:37:28-0300 [-] Creating router ...
2020-05-21T08:37:28-0300 [-] Initializing Router - Number of events: 1
2020-05-21T08:37:28-0300 [-] RouterFactory starting on 8081
2020-05-21T08:37:28-0300 [-] Creating AccessPoint station ...
2020-05-21T08:37:28-0300 [-] Initializing Access Point - Number of events: 2
2020-05-21T08:37:29-0300 [-] AccessPointFactory starting on 8082
2020-05-21T08:37:29-0300 [-] Creating fog node ...
2020-05-21T08:37:29-0300 [-] Initializing Client - Number of events: 3
2020-05-21T08:37:29-0300 [-] Creating fog node ...
2020-05-21T08:37:29-0300 [-] Initializing Client - Number of events: 4
2020-05-21T08:37:30-0300 [-] Creating fog node ...
2020-05-21T08:37:30-0300 [-] Initializing Server - Number of events: 5
2020-05-21T08:37:30-0300 [-] BrokerFactory starting on 5100
2020-05-21T08:37:30-0300 [-] Creating iot node ...
2020-05-21T08:37:30-0300 [-] Initializing Client - Number of events: 6
2020-05-21T08:37:31-0300 [-] Initializing sensor node - Number of events: 7
2020-05-21T08:37:31-0300 [-] Initializing sensor node - Number of events: 8
2020-05-21T08:37:32-0300 [-] Initializing sensor node - Number of events: 9
2020-05-21T08:37:33-0300 [-] Initializing sensor node - Number of events: 10
2020-05-21T08:37:33-0300 [-] Initializing sensor node - Number of events: 11
2020-05-21T08:37:34-0300 [-] Initializing sensor node - Number of events: 12
2020-05-21T08:37:34-0300 [-] Initializing sensor node - Number of events: 13
2020-05-21T08:37:35-0300 [-] Initializing sensor node - Number of events: 14
2020-05-21T08:37:35-0300 [-] Initializing sensor node - Number of events: 15
2020-05-21T08:37:36-0300 [-] Initializing sensor node - Number of events: 16
2020-05-21T08:37:36-0300 [stdout#info] ========= sensor_9 ==========
2020-05-21T08:37:36-0300 [stdout#info] =============================
2020-05-21T08:37:36-0300 [stdout#info] sensor_9 |12.74 Kwh
2020-05-21T08:37:36-0300 [stdout#info] sensor_9 |12.74 Kwh
2020-05-21T08:37:36-0300 [stdout#info] ========= sensor_3 ==========
2020-05-21T08:37:36-0300 [stdout#info] sensor_3  <------->  sensor_1
2020-05-21T08:37:36-0300 [stdout#info] sensor_3  <------->  sensor_4
2020-05-21T08:37:36-0300 [stdout#info] =============================
2020-05-21T08:37:36-0300 [stdout#info] sensor_3 |13.77 Kwh
2020-05-21T08:37:36-0300 [stdout#info] sensor_3 |13.77 Kwh
2020-05-21T08:37:36-0300 [stdout#info] ========= sensor_8 ==========
2020-05-21T08:37:36-0300 [stdout#info] sensor_8  <------->  sensor_7
2020-05-21T08:37:36-0300 [stdout#info] =============================
2020-05-21T08:37:36-0300 [stdout#info] sensor_8 |10.33 Kwh
2020-05-21T08:37:36-0300 [stdout#info] sensor_8 |10.33 Kwh
2020-05-21T08:37:36-0300 [stdout#info] ========= sensor_5 ==========
2020-05-21T08:37:36-0300 [stdout#info] sensor_5  <------->  sensor_6
2020-05-21T08:37:36-0300 [stdout#info] =============================
2020-05-21T08:37:36-0300 [stdout#info] sensor_5 |5.55 Kwh
2020-05-21T08:37:36-0300 [stdout#info] sensor_5 |5.55 Kwh
2020-05-21T08:37:36-0300 [stdout#info] ========= sensor_2 ==========
2020-05-21T08:37:36-0300 [stdout#info] =============================
2020-05-21T08:37:36-0300 [stdout#info] sensor_2 |7.53 Kwh
2020-05-21T08:37:36-0300 [stdout#info] sensor_2 |7.53 Kwh
2020-05-21T08:37:36-0300 [stdout#info] ========= sensor_1 ==========
2020-05-21T08:37:36-0300 [stdout#info] sensor_1  <------->  wsn_sink
2020-05-21T08:37:36-0300 [stdout#info] sensor_1  <------->  sensor_3
2020-05-21T08:37:36-0300 [stdout#info] =============================
2020-05-21T08:37:36-0300 [stdout#info] sensor_1 |7.87 Kwh|13.77 Kwh
2020-05-21T08:37:36-0300 [stdout#info] sensor_1 |7.87 Kwh|13.77 Kwh
2020-05-21T08:37:36-0300 [stdout#info] ========= sensor_7 ==========
2020-05-21T08:37:36-0300 [stdout#info] sensor_7  <------->  sensor_8
2020-05-21T08:37:36-0300 [stdout#info] =============================
2020-05-21T08:37:36-0300 [stdout#info] sensor_7 |10.33 Kwh|11.25 Kwh
2020-05-21T08:37:36-0300 [stdout#info] sensor_7 |10.33 Kwh|11.25 Kwh
2020-05-21T08:37:36-0300 [stdout#info] ========= sensor_4 ==========
2020-05-21T08:37:36-0300 [stdout#info] sensor_4  <------->  sensor_3
2020-05-21T08:37:36-0300 [stdout#info] =============================
2020-05-21T08:37:36-0300 [stdout#info] sensor_4 |16.01 Kwh|13.77 Kwh
2020-05-21T08:37:36-0300 [stdout#info] sensor_4 |16.01 Kwh|13.77 Kwh
2020-05-21T08:37:36-0300 [stdout#info] ========= sensor_6 ==========
2020-05-21T08:37:36-0300 [stdout#info] sensor_6  <------->  sensor_5
2020-05-21T08:37:36-0300 [stdout#info] =============================
2020-05-21T08:37:36-0300 [stdout#info] sensor_6 |12.4 Kwh|5.55 Kwh
2020-05-21T08:37:36-0300 [stdout#info] sensor_6 |12.4 Kwh|5.55 Kwh
2020-05-21T08:37:36-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:36-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:36-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:36-0300 [stderr#error]     func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:36-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:36-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:36-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:36-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:36-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:36-0300 [stderr#error]     func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:36-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:36-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:36-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:36-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:36-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:36-0300 [stderr#error]     func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:36-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:36-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:36-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:36-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:36-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:36-0300 [stderr#error]     func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:36-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:36-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:36-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:36-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:36-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:36-0300 [stderr#error]     func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:36-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:36-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:36-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:36-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:36-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:36-0300 [stderr#error]     func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:36-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:36-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:36-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:36-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:36-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:36-0300 [stderr#error]     func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:36-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:36-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:36-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:36-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:36-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:36-0300 [stderr#error]     func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:36-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:36-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:36-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:36-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:36-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:36-0300 [stderr#error]     func(*args)
2020-05-21T08:37:36-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:36-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:36-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:36-0300 [stdout#info] This divice have no simulation core instance
2020-05-21T08:37:36-0300 [stdout#info] This divice have no simulation core instance
2020-05-21T08:37:36-0300 [stdout#info] This divice have no simulation core instance
2020-05-21T08:37:36-0300 [stdout#info] This divice have no simulation core instance
2020-05-21T08:37:36-0300 [stdout#info] This divice have no simulation core instance
2020-05-21T08:37:36-0300 [Uninitialized] 127.0.0.1:33400 - Connected to mqtt broker - Number of events: 17
2020-05-21T08:37:36-0300 [Uninitialized] 127.0.0.1:33400 - sending MQTT SUBSCRIBE REQUEST - Number of events: 18
2020-05-21T08:37:36-0300 [Uninitialized] 127.0.0.1:33402 - Connected to mqtt broker - Number of events: 19
2020-05-21T08:37:36-0300 [Uninitialized] 127.0.0.1:33402 - sending MQTT SUBSCRIBE REQUEST - Number of events: 20
2020-05-21T08:37:36-0300 [Uninitialized] 127.0.0.1:52246 - Connected to mqtt broker - Number of events: 21
2020-05-21T08:37:36-0300 [Uninitialized] 127.0.0.1:52246 - sending MQTT PUBLISH REQUEST - Number of events: 22
2020-05-21T08:37:36-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab7eb5be0>
2020-05-21T08:37:36-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab7eb5dd8>
2020-05-21T08:37:36-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab953f048>
2020-05-21T08:37:36-0300 [stdout#info] This divice have no simulation core instance
2020-05-21T08:37:36-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab953f9b0>
2020-05-21T08:37:39-0300 [stdout#info] sensor_9 |12.74 Kwh|3.19 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_9 |12.74 Kwh|3.19 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_3 |7.87 Kwh|10.44 Kwh|16.01 Kwh|13.77 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_3 |7.87 Kwh|10.44 Kwh|16.01 Kwh|13.77 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_8 |10.33 Kwh|11.25 Kwh|14.99 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_8 |10.33 Kwh|11.25 Kwh|14.99 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_5 |12.4 Kwh|6.96 Kwh|5.55 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_5 |12.4 Kwh|6.96 Kwh|5.55 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_2 |16.9 Kwh|7.53 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_2 |16.9 Kwh|7.53 Kwh
2020-05-21T08:37:39-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:39-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:39-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:39-0300 [stderr#error]     func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:39-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:39-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:39-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:39-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:39-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:39-0300 [stderr#error]     func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:39-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:39-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:39-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:39-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:39-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:39-0300 [stderr#error]     func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:39-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:39-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:39-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:39-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:39-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:39-0300 [stderr#error]     func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:39-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:39-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:39-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:39-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:39-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:39-0300 [stderr#error]     func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:39-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:39-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:39-0300 [stdout#info] sensor_1 |7.87 Kwh|10.44 Kwh|19.65 Kwh|13.77 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_1 |7.87 Kwh|10.44 Kwh|19.65 Kwh|13.77 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_7 |10.33 Kwh|11.25 Kwh|6.35 Kwh|14.99 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_7 |10.33 Kwh|11.25 Kwh|6.35 Kwh|14.99 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_4 |6.08 Kwh|10.44 Kwh|16.01 Kwh|13.77 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_4 |6.08 Kwh|10.44 Kwh|16.01 Kwh|13.77 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_6 |12.4 Kwh|6.96 Kwh|12.55 Kwh|5.55 Kwh
2020-05-21T08:37:39-0300 [stdout#info] sensor_6 |12.4 Kwh|6.96 Kwh|12.55 Kwh|5.55 Kwh
2020-05-21T08:37:39-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:39-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:39-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:39-0300 [stderr#error]     func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:39-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:39-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:39-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:39-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:39-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:39-0300 [stderr#error]     func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:39-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:39-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:39-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:39-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:39-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:39-0300 [stderr#error]     func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:39-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:39-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:39-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:39-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:39-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:39-0300 [stderr#error]     func(*args)
2020-05-21T08:37:39-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:39-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:39-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:41-0300 [-] 127.0.0.1:52246 - sending MQTT PUBLISH REQUEST - Number of events: 23
2020-05-21T08:37:41-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab953fe80>
2020-05-21T08:37:41-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab953f048>
2020-05-21T08:37:41-0300 [stdout#info] This divice have no simulation core instance
2020-05-21T08:37:41-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab9552160>
2020-05-21T08:37:41-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab953f9b0>
2020-05-21T08:37:42-0300 [stdout#info] sensor_9 |12.74 Kwh|3.19 Kwh|9.9 Kwh
2020-05-21T08:37:42-0300 [stdout#info] sensor_9 |12.74 Kwh|3.19 Kwh|9.9 Kwh
2020-05-21T08:37:42-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:42-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:42-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:42-0300 [stderr#error]     func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:42-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:42-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:42-0300 [stdout#info] sensor_3 |16.01 Kwh|13.77 Kwh|7.87 Kwh|10.44 Kwh|6.08 Kwh|13.71 Kwh|19.65 Kwh
2020-05-21T08:37:42-0300 [stdout#info] sensor_3 |16.01 Kwh|13.77 Kwh|7.87 Kwh|10.44 Kwh|6.08 Kwh|13.71 Kwh|19.65 Kwh
2020-05-21T08:37:42-0300 [stdout#info] sensor_8 |10.33 Kwh|3.92 Kwh|6.35 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:42-0300 [stdout#info] sensor_8 |10.33 Kwh|3.92 Kwh|6.35 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:42-0300 [stdout#info] sensor_5 |12.55 Kwh|10.61 Kwh|12.4 Kwh|6.96 Kwh|5.55 Kwh
2020-05-21T08:37:42-0300 [stdout#info] sensor_5 |12.55 Kwh|10.61 Kwh|12.4 Kwh|6.96 Kwh|5.55 Kwh
2020-05-21T08:37:42-0300 [stdout#info] sensor_2 |16.9 Kwh|7.53 Kwh|17.13 Kwh
2020-05-21T08:37:42-0300 [stdout#info] sensor_2 |16.9 Kwh|7.53 Kwh|17.13 Kwh
2020-05-21T08:37:42-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:42-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:42-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:42-0300 [stderr#error]     func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:42-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:42-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:42-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:42-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:42-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:42-0300 [stderr#error]     func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:42-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:42-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:42-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:42-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:42-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:42-0300 [stderr#error]     func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:42-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:42-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:42-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:42-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:42-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:42-0300 [stderr#error]     func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:42-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:42-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:42-0300 [stdout#info] sensor_1 |21.12 Kwh|13.77 Kwh|7.87 Kwh|10.44 Kwh|13.71 Kwh|19.65 Kwh
2020-05-21T08:37:42-0300 [stdout#info] sensor_1 |21.12 Kwh|13.77 Kwh|7.87 Kwh|10.44 Kwh|13.71 Kwh|19.65 Kwh
2020-05-21T08:37:42-0300 [stdout#info] sensor_7 |10.33 Kwh|11.88 Kwh|3.92 Kwh|6.35 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:42-0300 [stdout#info] sensor_7 |10.33 Kwh|11.88 Kwh|3.92 Kwh|6.35 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:42-0300 [stdout#info] sensor_4 |16.01 Kwh|13.77 Kwh|2.77 Kwh|10.44 Kwh|6.08 Kwh|13.71 Kwh
2020-05-21T08:37:42-0300 [stdout#info] sensor_4 |16.01 Kwh|13.77 Kwh|2.77 Kwh|10.44 Kwh|6.08 Kwh|13.71 Kwh
2020-05-21T08:37:42-0300 [stdout#info] sensor_6 |12.55 Kwh|10.61 Kwh|10.43 Kwh|12.4 Kwh|6.96 Kwh|5.55 Kwh
2020-05-21T08:37:42-0300 [stdout#info] sensor_6 |12.55 Kwh|10.61 Kwh|10.43 Kwh|12.4 Kwh|6.96 Kwh|5.55 Kwh
2020-05-21T08:37:42-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:42-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:42-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:42-0300 [stderr#error]     func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:42-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:42-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:42-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:42-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:42-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:42-0300 [stderr#error]     func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:42-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:42-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:42-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:42-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:42-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:42-0300 [stderr#error]     func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:42-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:42-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:42-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:42-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:42-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:42-0300 [stderr#error]     func(*args)
2020-05-21T08:37:42-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:42-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:42-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:45-0300 [stdout#info] sensor_9 |11.84 Kwh|12.74 Kwh|3.19 Kwh|9.9 Kwh
2020-05-21T08:37:45-0300 [stdout#info] sensor_9 |11.84 Kwh|12.74 Kwh|3.19 Kwh|9.9 Kwh
2020-05-21T08:37:45-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:45-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:45-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:45-0300 [stderr#error]     func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:45-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:45-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:45-0300 [stdout#info] sensor_3 |21.12 Kwh|16.01 Kwh|13.77 Kwh|2.77 Kwh|7.87 Kwh|10.44 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|19.65 Kwh
2020-05-21T08:37:45-0300 [stdout#info] sensor_3 |21.12 Kwh|16.01 Kwh|13.77 Kwh|2.77 Kwh|7.87 Kwh|10.44 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|19.65 Kwh
2020-05-21T08:37:45-0300 [stdout#info] sensor_8 |10.33 Kwh|20.09 Kwh|11.88 Kwh|3.92 Kwh|6.35 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:45-0300 [stdout#info] sensor_8 |10.33 Kwh|20.09 Kwh|11.88 Kwh|3.92 Kwh|6.35 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:45-0300 [stdout#info] sensor_5 |12.55 Kwh|10.61 Kwh|10.43 Kwh|12.4 Kwh|6.96 Kwh|5.55 Kwh|7.82 Kwh
2020-05-21T08:37:45-0300 [stdout#info] sensor_5 |12.55 Kwh|10.61 Kwh|10.43 Kwh|12.4 Kwh|6.96 Kwh|5.55 Kwh|7.82 Kwh
2020-05-21T08:37:45-0300 [stdout#info] sensor_2 |16.9 Kwh|12.86 Kwh|7.53 Kwh|17.13 Kwh
2020-05-21T08:37:45-0300 [stdout#info] sensor_2 |16.9 Kwh|12.86 Kwh|7.53 Kwh|17.13 Kwh
2020-05-21T08:37:45-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:45-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:45-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:45-0300 [stderr#error]     func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:45-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:45-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:45-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:45-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:45-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:45-0300 [stderr#error]     func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:45-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:45-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:45-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:45-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:45-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:45-0300 [stderr#error]     func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:45-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:45-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:45-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:45-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:45-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:45-0300 [stderr#error]     func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:45-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:45-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:45-0300 [stdout#info] sensor_1 |21.12 Kwh|13.77 Kwh|16.57 Kwh|7.87 Kwh|10.44 Kwh|13.71 Kwh|5.72 Kwh|19.65 Kwh
2020-05-21T08:37:45-0300 [stdout#info] sensor_1 |21.12 Kwh|13.77 Kwh|16.57 Kwh|7.87 Kwh|10.44 Kwh|13.71 Kwh|5.72 Kwh|19.65 Kwh
2020-05-21T08:37:45-0300 [stdout#info] sensor_7 |10.33 Kwh|4.15 Kwh|20.09 Kwh|11.88 Kwh|3.92 Kwh|6.35 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:45-0300 [stdout#info] sensor_7 |10.33 Kwh|4.15 Kwh|20.09 Kwh|11.88 Kwh|3.92 Kwh|6.35 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:45-0300 [stdout#info] sensor_4 |16.01 Kwh|13.77 Kwh|19.28 Kwh|2.77 Kwh|10.44 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh
2020-05-21T08:37:45-0300 [stdout#info] sensor_4 |16.01 Kwh|13.77 Kwh|19.28 Kwh|2.77 Kwh|10.44 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh
2020-05-21T08:37:45-0300 [stdout#info] sensor_6 |12.55 Kwh|10.61 Kwh|10.43 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|5.55 Kwh|7.82 Kwh
2020-05-21T08:37:45-0300 [stdout#info] sensor_6 |12.55 Kwh|10.61 Kwh|10.43 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|5.55 Kwh|7.82 Kwh
2020-05-21T08:37:45-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:45-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:45-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:45-0300 [stderr#error]     func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:45-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:45-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:45-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:45-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:45-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:45-0300 [stderr#error]     func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:45-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:45-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:45-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:45-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:45-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:45-0300 [stderr#error]     func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:45-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:45-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:45-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:45-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:45-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:45-0300 [stderr#error]     func(*args)
2020-05-21T08:37:45-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:45-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:45-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:46-0300 [-] 127.0.0.1:52246 - sending MQTT PUBLISH REQUEST - Number of events: 24
2020-05-21T08:37:46-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab95525f8>
2020-05-21T08:37:46-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab953fe80>
2020-05-21T08:37:46-0300 [stdout#info] This divice have no simulation core instance
2020-05-21T08:37:46-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab9552898>
2020-05-21T08:37:48-0300 [stdout#info] sensor_9 |12.74 Kwh|3.19 Kwh|9.9 Kwh|11.84 Kwh|21.25 Kwh
2020-05-21T08:37:48-0300 [stdout#info] sensor_9 |12.74 Kwh|3.19 Kwh|9.9 Kwh|11.84 Kwh|21.25 Kwh
2020-05-21T08:37:48-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:48-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:48-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:48-0300 [stderr#error]     func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:48-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:48-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:48-0300 [stdout#info] sensor_3 |21.12 Kwh|16.01 Kwh|13.77 Kwh|22.24 Kwh|16.57 Kwh|19.28 Kwh|2.77 Kwh|7.87 Kwh|10.44 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|19.65 Kwh
2020-05-21T08:37:48-0300 [stdout#info] sensor_3 |21.12 Kwh|16.01 Kwh|13.77 Kwh|22.24 Kwh|16.57 Kwh|19.28 Kwh|2.77 Kwh|7.87 Kwh|10.44 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|19.65 Kwh
2020-05-21T08:37:48-0300 [stdout#info] sensor_8 |10.33 Kwh|4.15 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.92 Kwh|6.35 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:48-0300 [stdout#info] sensor_8 |10.33 Kwh|4.15 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.92 Kwh|6.35 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:48-0300 [stdout#info] sensor_5 |12.55 Kwh|7.7 Kwh|10.61 Kwh|10.43 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|5.55 Kwh|7.82 Kwh
2020-05-21T08:37:48-0300 [stdout#info] sensor_5 |12.55 Kwh|7.7 Kwh|10.61 Kwh|10.43 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|5.55 Kwh|7.82 Kwh
2020-05-21T08:37:48-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:48-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:48-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:48-0300 [stderr#error]     func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:48-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:48-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:48-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:48-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:48-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:48-0300 [stderr#error]     func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:48-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:48-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:48-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:48-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:48-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:48-0300 [stderr#error]     func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:48-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:48-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:48-0300 [stdout#info] sensor_2 |7.53 Kwh|3.29 Kwh|17.13 Kwh|12.86 Kwh|16.9 Kwh
2020-05-21T08:37:48-0300 [stdout#info] sensor_2 |7.53 Kwh|3.29 Kwh|17.13 Kwh|12.86 Kwh|16.9 Kwh
2020-05-21T08:37:48-0300 [stdout#info] sensor_1 |21.12 Kwh|13.77 Kwh|16.57 Kwh|7.01 Kwh|7.87 Kwh|10.44 Kwh|22.24 Kwh|13.71 Kwh|5.72 Kwh|19.65 Kwh
2020-05-21T08:37:48-0300 [stdout#info] sensor_1 |21.12 Kwh|13.77 Kwh|16.57 Kwh|7.01 Kwh|7.87 Kwh|10.44 Kwh|22.24 Kwh|13.71 Kwh|5.72 Kwh|19.65 Kwh
2020-05-21T08:37:48-0300 [stdout#info] sensor_7 |10.33 Kwh|4.15 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.92 Kwh|6.35 Kwh|4.24 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:48-0300 [stdout#info] sensor_7 |10.33 Kwh|4.15 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.92 Kwh|6.35 Kwh|4.24 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:48-0300 [stdout#info] sensor_4 |16.01 Kwh|13.77 Kwh|22.24 Kwh|19.28 Kwh|2.77 Kwh|10.44 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|7.08 Kwh
2020-05-21T08:37:48-0300 [stdout#info] sensor_4 |16.01 Kwh|13.77 Kwh|22.24 Kwh|19.28 Kwh|2.77 Kwh|10.44 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|7.08 Kwh
2020-05-21T08:37:48-0300 [stdout#info] sensor_6 |12.55 Kwh|7.7 Kwh|10.61 Kwh|10.43 Kwh|10.76 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|5.55 Kwh|7.82 Kwh
2020-05-21T08:37:48-0300 [stdout#info] sensor_6 |12.55 Kwh|7.7 Kwh|10.61 Kwh|10.43 Kwh|10.76 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|5.55 Kwh|7.82 Kwh
2020-05-21T08:37:48-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:48-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:48-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:48-0300 [stderr#error]     func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:48-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:48-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:48-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:48-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:48-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:48-0300 [stderr#error]     func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:48-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:48-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:48-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:48-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:48-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:48-0300 [stderr#error]     func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:48-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:48-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:48-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:48-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:48-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:48-0300 [stderr#error]     func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:48-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:48-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:48-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:48-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:48-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:48-0300 [stderr#error]     func(*args)
2020-05-21T08:37:48-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:48-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:48-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:51-0300 [stdout#info] sensor_9 |12.74 Kwh|3.19 Kwh|9.9 Kwh|11.84 Kwh|8.15 Kwh|21.25 Kwh
2020-05-21T08:37:51-0300 [stdout#info] sensor_9 |12.74 Kwh|3.19 Kwh|9.9 Kwh|11.84 Kwh|8.15 Kwh|21.25 Kwh
2020-05-21T08:37:51-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:51-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:51-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:51-0300 [stderr#error]     func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:51-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:51-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:51-0300 [stdout#info] sensor_3 |21.12 Kwh|16.01 Kwh|13.77 Kwh|22.24 Kwh|16.57 Kwh|19.28 Kwh|3.19 Kwh|2.77 Kwh|7.87 Kwh|7.01 Kwh|10.44 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|7.08 Kwh|19.65 Kwh
2020-05-21T08:37:51-0300 [stdout#info] sensor_3 |21.12 Kwh|16.01 Kwh|13.77 Kwh|22.24 Kwh|16.57 Kwh|19.28 Kwh|3.19 Kwh|2.77 Kwh|7.87 Kwh|7.01 Kwh|10.44 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|7.08 Kwh|19.65 Kwh
2020-05-21T08:37:51-0300 [stdout#info] sensor_8 |10.33 Kwh|4.15 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|6.35 Kwh|4.24 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:51-0300 [stdout#info] sensor_8 |10.33 Kwh|4.15 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|6.35 Kwh|4.24 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:51-0300 [stdout#info] sensor_5 |12.55 Kwh|7.7 Kwh|10.61 Kwh|10.43 Kwh|10.76 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh
2020-05-21T08:37:51-0300 [stdout#info] sensor_5 |12.55 Kwh|7.7 Kwh|10.61 Kwh|10.43 Kwh|10.76 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh
2020-05-21T08:37:51-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:51-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:51-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:51-0300 [stderr#error]     func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:51-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:51-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:51-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:51-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:51-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:51-0300 [stderr#error]     func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:51-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:51-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:51-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:51-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:51-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:51-0300 [stderr#error]     func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:51-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:51-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:51-0300 [stdout#info] sensor_2 |7.53 Kwh|14.84 Kwh|3.29 Kwh|17.13 Kwh|12.86 Kwh|16.9 Kwh
2020-05-21T08:37:51-0300 [stdout#info] sensor_2 |7.53 Kwh|14.84 Kwh|3.29 Kwh|17.13 Kwh|12.86 Kwh|16.9 Kwh
2020-05-21T08:37:51-0300 [stdout#info] sensor_1 |21.12 Kwh|14.2 Kwh|13.77 Kwh|16.57 Kwh|3.19 Kwh|7.01 Kwh|7.87 Kwh|10.44 Kwh|22.24 Kwh|13.71 Kwh|5.72 Kwh|19.65 Kwh
2020-05-21T08:37:51-0300 [stdout#info] sensor_1 |21.12 Kwh|14.2 Kwh|13.77 Kwh|16.57 Kwh|3.19 Kwh|7.01 Kwh|7.87 Kwh|10.44 Kwh|22.24 Kwh|13.71 Kwh|5.72 Kwh|19.65 Kwh
2020-05-21T08:37:51-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:51-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:51-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:51-0300 [stderr#error]     func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:51-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:51-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:51-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:51-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:51-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:51-0300 [stderr#error]     func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:51-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:51-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:51-0300 [stdout#info] sensor_7 |10.33 Kwh|4.15 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|6.35 Kwh|4.24 Kwh|19.3 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:51-0300 [stdout#info] sensor_7 |10.33 Kwh|4.15 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|6.35 Kwh|4.24 Kwh|19.3 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:51-0300 [stdout#info] sensor_4 |16.01 Kwh|13.77 Kwh|22.24 Kwh|3.19 Kwh|19.28 Kwh|2.77 Kwh|10.44 Kwh|10.25 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|7.08 Kwh
2020-05-21T08:37:51-0300 [stdout#info] sensor_4 |16.01 Kwh|13.77 Kwh|22.24 Kwh|3.19 Kwh|19.28 Kwh|2.77 Kwh|10.44 Kwh|10.25 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|7.08 Kwh
2020-05-21T08:37:51-0300 [stdout#info] sensor_6 |12.55 Kwh|7.7 Kwh|10.61 Kwh|10.43 Kwh|10.76 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh|2.71 Kwh
2020-05-21T08:37:51-0300 [stdout#info] sensor_6 |12.55 Kwh|7.7 Kwh|10.61 Kwh|10.43 Kwh|10.76 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh|2.71 Kwh
2020-05-21T08:37:51-0300 [-] 127.0.0.1:52246 - sending MQTT PUBLISH REQUEST - Number of events: 25
2020-05-21T08:37:51-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:51-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:51-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:51-0300 [stderr#error]     func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:51-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:51-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:51-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:51-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:51-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:51-0300 [stderr#error]     func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:51-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:51-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:51-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:51-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:51-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:51-0300 [stderr#error]     func(*args)
2020-05-21T08:37:51-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:51-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:51-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:51-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab9552f60>
2020-05-21T08:37:51-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab95525f8>
2020-05-21T08:37:51-0300 [stdout#info] This divice have no simulation core instance
2020-05-21T08:37:51-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab956d240>
2020-05-21T08:37:54-0300 [stdout#info] sensor_9 |12.74 Kwh|3.19 Kwh|9.9 Kwh|11.84 Kwh|20.45 Kwh|8.15 Kwh|21.25 Kwh
2020-05-21T08:37:54-0300 [stdout#info] sensor_9 |12.74 Kwh|3.19 Kwh|9.9 Kwh|11.84 Kwh|20.45 Kwh|8.15 Kwh|21.25 Kwh
2020-05-21T08:37:54-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:54-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:54-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:54-0300 [stderr#error]     func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:54-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:54-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:54-0300 [stdout#info] sensor_3 |21.12 Kwh|14.2 Kwh|16.01 Kwh|13.77 Kwh|16.95 Kwh|22.24 Kwh|16.57 Kwh|19.28 Kwh|3.19 Kwh|2.77 Kwh|7.87 Kwh|7.01 Kwh|10.44 Kwh|10.25 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|7.08 Kwh|19.65 Kwh
2020-05-21T08:37:54-0300 [stdout#info] sensor_3 |21.12 Kwh|14.2 Kwh|16.01 Kwh|13.77 Kwh|16.95 Kwh|22.24 Kwh|16.57 Kwh|19.28 Kwh|3.19 Kwh|2.77 Kwh|7.87 Kwh|7.01 Kwh|10.44 Kwh|10.25 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|7.08 Kwh|19.65 Kwh
2020-05-21T08:37:54-0300 [stdout#info] sensor_8 |10.33 Kwh|4.15 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|21.02 Kwh|6.35 Kwh|4.24 Kwh|19.3 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:54-0300 [stdout#info] sensor_8 |10.33 Kwh|4.15 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|21.02 Kwh|6.35 Kwh|4.24 Kwh|19.3 Kwh|14.99 Kwh|11.25 Kwh
2020-05-21T08:37:54-0300 [stdout#info] sensor_5 |12.55 Kwh|7.7 Kwh|10.61 Kwh|10.43 Kwh|10.76 Kwh|3.04 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh|2.71 Kwh
2020-05-21T08:37:54-0300 [stdout#info] sensor_5 |12.55 Kwh|7.7 Kwh|10.61 Kwh|10.43 Kwh|10.76 Kwh|3.04 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh|2.71 Kwh
2020-05-21T08:37:54-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:54-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:54-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:54-0300 [stderr#error]     func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:54-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:54-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:54-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:54-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:54-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:54-0300 [stderr#error]     func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:54-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:54-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:54-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:54-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:54-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:54-0300 [stderr#error]     func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:54-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:54-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:54-0300 [stdout#info] sensor_2 |9.33 Kwh|7.53 Kwh|14.84 Kwh|3.29 Kwh|17.13 Kwh|12.86 Kwh|16.9 Kwh
2020-05-21T08:37:54-0300 [stdout#info] sensor_2 |9.33 Kwh|7.53 Kwh|14.84 Kwh|3.29 Kwh|17.13 Kwh|12.86 Kwh|16.9 Kwh
2020-05-21T08:37:54-0300 [stdout#info] sensor_1 |21.12 Kwh|14.2 Kwh|16.95 Kwh|13.77 Kwh|16.57 Kwh|3.19 Kwh|7.01 Kwh|7.87 Kwh|18.38 Kwh|10.44 Kwh|22.24 Kwh|13.71 Kwh|5.72 Kwh|19.65 Kwh
2020-05-21T08:37:54-0300 [stdout#info] sensor_1 |21.12 Kwh|14.2 Kwh|16.95 Kwh|13.77 Kwh|16.57 Kwh|3.19 Kwh|7.01 Kwh|7.87 Kwh|18.38 Kwh|10.44 Kwh|22.24 Kwh|13.71 Kwh|5.72 Kwh|19.65 Kwh
2020-05-21T08:37:54-0300 [stdout#info] sensor_7 |10.33 Kwh|4.15 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|21.02 Kwh|6.35 Kwh|4.24 Kwh|19.3 Kwh|14.99 Kwh|8.28 Kwh|11.25 Kwh
2020-05-21T08:37:54-0300 [stdout#info] sensor_7 |10.33 Kwh|4.15 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|21.02 Kwh|6.35 Kwh|4.24 Kwh|19.3 Kwh|14.99 Kwh|8.28 Kwh|11.25 Kwh
2020-05-21T08:37:54-0300 [stdout#info] sensor_4 |16.95 Kwh|16.01 Kwh|13.77 Kwh|22.24 Kwh|3.19 Kwh|19.28 Kwh|2.77 Kwh|10.44 Kwh|12.71 Kwh|10.25 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|7.08 Kwh
2020-05-21T08:37:54-0300 [stdout#info] sensor_4 |16.95 Kwh|16.01 Kwh|13.77 Kwh|22.24 Kwh|3.19 Kwh|19.28 Kwh|2.77 Kwh|10.44 Kwh|12.71 Kwh|10.25 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|7.08 Kwh
2020-05-21T08:37:54-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:54-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:54-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:54-0300 [stderr#error]     func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:54-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:54-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:54-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:54-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:54-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:54-0300 [stderr#error]     func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:54-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:54-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:54-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:54-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:54-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:54-0300 [stderr#error]     func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:54-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:54-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:54-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:54-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:54-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:54-0300 [stderr#error]     func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:54-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:54-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:54-0300 [stdout#info] sensor_6 |12.55 Kwh|7.7 Kwh|10.61 Kwh|10.43 Kwh|17.4 Kwh|10.76 Kwh|3.04 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh|2.71 Kwh
2020-05-21T08:37:54-0300 [stdout#info] sensor_6 |12.55 Kwh|7.7 Kwh|10.61 Kwh|10.43 Kwh|17.4 Kwh|10.76 Kwh|3.04 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh|2.71 Kwh
2020-05-21T08:37:54-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:54-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:54-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:54-0300 [stderr#error]     func(*args)
2020-05-21T08:37:54-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:54-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:54-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:56-0300 [-] 127.0.0.1:52246 - sending MQTT PUBLISH REQUEST - Number of events: 26
2020-05-21T08:37:56-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab956d6a0>
2020-05-21T08:37:56-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab9552f60>
2020-05-21T08:37:56-0300 [stdout#info] This divice have no simulation core instance
2020-05-21T08:37:56-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab956d908>
2020-05-21T08:37:57-0300 [stdout#info] sensor_9 |14.4 Kwh|12.74 Kwh|3.19 Kwh|9.9 Kwh|11.84 Kwh|20.45 Kwh|8.15 Kwh|21.25 Kwh
2020-05-21T08:37:57-0300 [stdout#info] sensor_9 |14.4 Kwh|12.74 Kwh|3.19 Kwh|9.9 Kwh|11.84 Kwh|20.45 Kwh|8.15 Kwh|21.25 Kwh
2020-05-21T08:37:57-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:57-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:57-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:57-0300 [stderr#error]     func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:57-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:57-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:57-0300 [stdout#info] sensor_3 |16.01 Kwh|19.28 Kwh|2.77 Kwh|13.71 Kwh|14.2 Kwh|13.77 Kwh|16.57 Kwh|3.19 Kwh|7.01 Kwh|10.44 Kwh|12.71 Kwh|10.25 Kwh|7.08 Kwh|11.0 Kwh|16.95 Kwh|18.38 Kwh|22.24 Kwh|5.72 Kwh|21.12 Kwh|7.87 Kwh|6.08 Kwh|19.65 Kwh
2020-05-21T08:37:57-0300 [stdout#info] sensor_3 |16.01 Kwh|19.28 Kwh|2.77 Kwh|13.71 Kwh|14.2 Kwh|13.77 Kwh|16.57 Kwh|3.19 Kwh|7.01 Kwh|10.44 Kwh|12.71 Kwh|10.25 Kwh|7.08 Kwh|11.0 Kwh|16.95 Kwh|18.38 Kwh|22.24 Kwh|5.72 Kwh|21.12 Kwh|7.87 Kwh|6.08 Kwh|19.65 Kwh
2020-05-21T08:37:57-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:57-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:57-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:57-0300 [stderr#error]     func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:57-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:57-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:57-0300 [stdout#info] sensor_8 |10.33 Kwh|4.15 Kwh|13.32 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|21.02 Kwh|6.35 Kwh|4.24 Kwh|19.3 Kwh|14.99 Kwh|8.28 Kwh|11.25 Kwh
2020-05-21T08:37:57-0300 [stdout#info] sensor_8 |10.33 Kwh|4.15 Kwh|13.32 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|21.02 Kwh|6.35 Kwh|4.24 Kwh|19.3 Kwh|14.99 Kwh|8.28 Kwh|11.25 Kwh
2020-05-21T08:37:57-0300 [stdout#info] sensor_5 |12.55 Kwh|7.7 Kwh|8.74 Kwh|10.61 Kwh|10.43 Kwh|17.4 Kwh|10.76 Kwh|3.04 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh|2.71 Kwh
2020-05-21T08:37:57-0300 [stdout#info] sensor_5 |12.55 Kwh|7.7 Kwh|8.74 Kwh|10.61 Kwh|10.43 Kwh|17.4 Kwh|10.76 Kwh|3.04 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh|2.71 Kwh
2020-05-21T08:37:57-0300 [stdout#info] sensor_2 |9.33 Kwh|7.53 Kwh|14.84 Kwh|3.29 Kwh|17.13 Kwh|15.8 Kwh|12.86 Kwh|16.9 Kwh
2020-05-21T08:37:57-0300 [stdout#info] sensor_2 |9.33 Kwh|7.53 Kwh|14.84 Kwh|3.29 Kwh|17.13 Kwh|15.8 Kwh|12.86 Kwh|16.9 Kwh
2020-05-21T08:37:57-0300 [stdout#info] sensor_1 |11.0 Kwh|21.12 Kwh|14.2 Kwh|16.95 Kwh|13.77 Kwh|16.57 Kwh|3.19 Kwh|7.01 Kwh|7.87 Kwh|18.38 Kwh|10.44 Kwh|22.24 Kwh|13.71 Kwh|5.72 Kwh|6.51 Kwh|19.65 Kwh
2020-05-21T08:37:57-0300 [stdout#info] sensor_1 |11.0 Kwh|21.12 Kwh|14.2 Kwh|16.95 Kwh|13.77 Kwh|16.57 Kwh|3.19 Kwh|7.01 Kwh|7.87 Kwh|18.38 Kwh|10.44 Kwh|22.24 Kwh|13.71 Kwh|5.72 Kwh|6.51 Kwh|19.65 Kwh
2020-05-21T08:37:57-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:57-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:57-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:57-0300 [stderr#error]     func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:57-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:57-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:57-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:57-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:57-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:57-0300 [stderr#error]     func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:57-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:57-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:57-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:57-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:57-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:57-0300 [stderr#error]     func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:57-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:57-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:57-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:57-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:57-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:57-0300 [stderr#error]     func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:57-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:57-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:57-0300 [stdout#info] sensor_7 |10.33 Kwh|4.15 Kwh|13.32 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|17.76 Kwh|21.02 Kwh|6.35 Kwh|4.24 Kwh|19.3 Kwh|14.99 Kwh|8.28 Kwh|11.25 Kwh
2020-05-21T08:37:57-0300 [stdout#info] sensor_7 |10.33 Kwh|4.15 Kwh|13.32 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|17.76 Kwh|21.02 Kwh|6.35 Kwh|4.24 Kwh|19.3 Kwh|14.99 Kwh|8.28 Kwh|11.25 Kwh
2020-05-21T08:37:57-0300 [stdout#info] sensor_4 |11.0 Kwh|16.95 Kwh|16.01 Kwh|13.77 Kwh|20.72 Kwh|22.24 Kwh|3.19 Kwh|19.28 Kwh|2.77 Kwh|10.44 Kwh|12.71 Kwh|10.25 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|7.08 Kwh
2020-05-21T08:37:57-0300 [stdout#info] sensor_4 |11.0 Kwh|16.95 Kwh|16.01 Kwh|13.77 Kwh|20.72 Kwh|22.24 Kwh|3.19 Kwh|19.28 Kwh|2.77 Kwh|10.44 Kwh|12.71 Kwh|10.25 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|7.08 Kwh
2020-05-21T08:37:57-0300 [stdout#info] sensor_6 |12.55 Kwh|7.7 Kwh|8.74 Kwh|10.61 Kwh|14.73 Kwh|10.43 Kwh|17.4 Kwh|10.76 Kwh|3.04 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh|2.71 Kwh
2020-05-21T08:37:57-0300 [stdout#info] sensor_6 |12.55 Kwh|7.7 Kwh|8.74 Kwh|10.61 Kwh|14.73 Kwh|10.43 Kwh|17.4 Kwh|10.76 Kwh|3.04 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh|2.71 Kwh
2020-05-21T08:37:57-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:57-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:57-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:57-0300 [stderr#error]     func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:57-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:57-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:57-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:57-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:57-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:57-0300 [stderr#error]     func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:57-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:57-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:37:57-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:37:57-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:37:57-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:37:57-0300 [stderr#error]     func(*args)
2020-05-21T08:37:57-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:37:57-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:37:57-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:38:00-0300 [stdout#info] sensor_9 |14.4 Kwh|12.74 Kwh|3.19 Kwh|9.9 Kwh|11.84 Kwh|20.45 Kwh|8.15 Kwh|3.25 Kwh|21.25 Kwh
2020-05-21T08:38:00-0300 [stdout#info] sensor_9 |14.4 Kwh|12.74 Kwh|3.19 Kwh|9.9 Kwh|11.84 Kwh|20.45 Kwh|8.15 Kwh|3.25 Kwh|21.25 Kwh
2020-05-21T08:38:00-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:38:00-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:38:00-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:38:00-0300 [stderr#error]     func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:38:00-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:38:00-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:38:00-0300 [stdout#info] sensor_3 |16.01 Kwh|19.28 Kwh|2.77 Kwh|13.71 Kwh|14.2 Kwh|13.77 Kwh|16.57 Kwh|3.19 Kwh|7.01 Kwh|10.44 Kwh|12.71 Kwh|10.25 Kwh|18.45 Kwh|7.08 Kwh|11.0 Kwh|16.95 Kwh|20.72 Kwh|18.38 Kwh|22.24 Kwh|5.72 Kwh|6.51 Kwh|21.12 Kwh|7.87 Kwh|6.08 Kwh|19.65 Kwh
2020-05-21T08:38:00-0300 [stdout#info] sensor_3 |16.01 Kwh|19.28 Kwh|2.77 Kwh|13.71 Kwh|14.2 Kwh|13.77 Kwh|16.57 Kwh|3.19 Kwh|7.01 Kwh|10.44 Kwh|12.71 Kwh|10.25 Kwh|18.45 Kwh|7.08 Kwh|11.0 Kwh|16.95 Kwh|20.72 Kwh|18.38 Kwh|22.24 Kwh|5.72 Kwh|6.51 Kwh|21.12 Kwh|7.87 Kwh|6.08 Kwh|19.65 Kwh
2020-05-21T08:38:00-0300 [stdout#info] sensor_8 |10.33 Kwh|4.15 Kwh|13.32 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|17.76 Kwh|21.02 Kwh|6.35 Kwh|6.38 Kwh|4.24 Kwh|19.3 Kwh|14.99 Kwh|8.28 Kwh|11.25 Kwh
2020-05-21T08:38:00-0300 [stdout#info] sensor_8 |10.33 Kwh|4.15 Kwh|13.32 Kwh|20.09 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|17.76 Kwh|21.02 Kwh|6.35 Kwh|6.38 Kwh|4.24 Kwh|19.3 Kwh|14.99 Kwh|8.28 Kwh|11.25 Kwh
2020-05-21T08:38:00-0300 [stdout#info] sensor_5 |12.55 Kwh|7.7 Kwh|8.74 Kwh|10.61 Kwh|14.73 Kwh|10.43 Kwh|10.89 Kwh|17.4 Kwh|10.76 Kwh|3.04 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh|2.71 Kwh
2020-05-21T08:38:00-0300 [stdout#info] sensor_5 |12.55 Kwh|7.7 Kwh|8.74 Kwh|10.61 Kwh|14.73 Kwh|10.43 Kwh|10.89 Kwh|17.4 Kwh|10.76 Kwh|3.04 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh|2.71 Kwh
2020-05-21T08:38:00-0300 [stdout#info] sensor_2 |9.33 Kwh|7.53 Kwh|14.84 Kwh|16.43 Kwh|3.29 Kwh|17.13 Kwh|15.8 Kwh|12.86 Kwh|16.9 Kwh
2020-05-21T08:38:00-0300 [stdout#info] sensor_2 |9.33 Kwh|7.53 Kwh|14.84 Kwh|16.43 Kwh|3.29 Kwh|17.13 Kwh|15.8 Kwh|12.86 Kwh|16.9 Kwh
2020-05-21T08:38:00-0300 [stdout#info] sensor_1 |11.0 Kwh|21.12 Kwh|14.2 Kwh|16.95 Kwh|13.77 Kwh|13.08 Kwh|16.57 Kwh|3.19 Kwh|7.01 Kwh|7.87 Kwh|18.38 Kwh|10.44 Kwh|18.45 Kwh|22.24 Kwh|13.71 Kwh|5.72 Kwh|6.51 Kwh|19.65 Kwh
2020-05-21T08:38:00-0300 [stdout#info] sensor_1 |11.0 Kwh|21.12 Kwh|14.2 Kwh|16.95 Kwh|13.77 Kwh|13.08 Kwh|16.57 Kwh|3.19 Kwh|7.01 Kwh|7.87 Kwh|18.38 Kwh|10.44 Kwh|18.45 Kwh|22.24 Kwh|13.71 Kwh|5.72 Kwh|6.51 Kwh|19.65 Kwh
2020-05-21T08:38:00-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:38:00-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:38:00-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:38:00-0300 [stderr#error]     func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:38:00-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:38:00-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:38:00-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:38:00-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:38:00-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:38:00-0300 [stderr#error]     func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:38:00-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:38:00-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:38:00-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:38:00-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:38:00-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:38:00-0300 [stderr#error]     func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:38:00-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:38:00-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:38:00-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:38:00-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:38:00-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:38:00-0300 [stderr#error]     func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:38:00-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:38:00-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:38:00-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:38:00-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:38:00-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:38:00-0300 [stderr#error]     func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:38:00-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:38:00-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:38:00-0300 [stdout#info] sensor_7 |10.33 Kwh|4.15 Kwh|13.32 Kwh|20.09 Kwh|12.46 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|17.76 Kwh|21.02 Kwh|6.35 Kwh|6.38 Kwh|4.24 Kwh|19.3 Kwh|14.99 Kwh|8.28 Kwh|11.25 Kwh
2020-05-21T08:38:00-0300 [stdout#info] sensor_7 |10.33 Kwh|4.15 Kwh|13.32 Kwh|20.09 Kwh|12.46 Kwh|18.11 Kwh|11.88 Kwh|3.66 Kwh|3.92 Kwh|17.76 Kwh|21.02 Kwh|6.35 Kwh|6.38 Kwh|4.24 Kwh|19.3 Kwh|14.99 Kwh|8.28 Kwh|11.25 Kwh
2020-05-21T08:38:00-0300 [stdout#info] sensor_4 |11.0 Kwh|16.7 Kwh|16.95 Kwh|16.01 Kwh|13.77 Kwh|20.72 Kwh|22.24 Kwh|3.19 Kwh|19.28 Kwh|2.77 Kwh|10.44 Kwh|12.71 Kwh|10.25 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|18.45 Kwh|7.08 Kwh
2020-05-21T08:38:00-0300 [stdout#info] sensor_4 |11.0 Kwh|16.7 Kwh|16.95 Kwh|16.01 Kwh|13.77 Kwh|20.72 Kwh|22.24 Kwh|3.19 Kwh|19.28 Kwh|2.77 Kwh|10.44 Kwh|12.71 Kwh|10.25 Kwh|6.08 Kwh|13.71 Kwh|5.72 Kwh|18.45 Kwh|7.08 Kwh
2020-05-21T08:38:00-0300 [stdout#info] sensor_6 |12.55 Kwh|7.7 Kwh|8.74 Kwh|10.61 Kwh|14.73 Kwh|10.43 Kwh|10.89 Kwh|4.66 Kwh|17.4 Kwh|10.76 Kwh|3.04 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh|2.71 Kwh
2020-05-21T08:38:00-0300 [stdout#info] sensor_6 |12.55 Kwh|7.7 Kwh|8.74 Kwh|10.61 Kwh|14.73 Kwh|10.43 Kwh|10.89 Kwh|4.66 Kwh|17.4 Kwh|10.76 Kwh|3.04 Kwh|12.4 Kwh|6.96 Kwh|21.65 Kwh|21.59 Kwh|5.55 Kwh|7.82 Kwh|2.71 Kwh
2020-05-21T08:38:00-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:38:00-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:38:00-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:38:00-0300 [stderr#error]     func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:38:00-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:38:00-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:38:00-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:38:00-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:38:00-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:38:00-0300 [stderr#error]     func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:38:00-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:38:00-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:38:00-0300 [stderr#error] Exception in Tkinter callback
2020-05-21T08:38:00-0300 [stderr#error] Traceback (most recent call last):
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-21T08:38:00-0300 [stderr#error]     return self.func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 752, in callit
2020-05-21T08:38:00-0300 [stderr#error]     func(*args)
2020-05-21T08:38:00-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 48, in remove_sent_packages_from_buffer
2020-05-21T08:38:00-0300 [stderr#error]     self._buffer = self._buffer - sel.ftemp_buffer
2020-05-21T08:38:00-0300 [stderr#error] NameError: name 'sel' is not defined
2020-05-21T08:38:01-0300 [-] 127.0.0.1:52246 - sending MQTT PUBLISH REQUEST - Number of events: 27
2020-05-21T08:38:01-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab956de48>
2020-05-21T08:38:01-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab956d6a0>
2020-05-21T08:38:01-0300 [stdout#info] This divice have no simulation core instance
2020-05-21T08:38:01-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab95040f0>
2020-05-21T08:38:03-0300 [-] Received SIGINT, shutting down.
2020-05-21T08:38:03-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab7eb5be0>
2020-05-21T08:38:03-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab9552898>
2020-05-21T08:38:03-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab95040f0>
2020-05-21T08:38:03-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab956d908>
2020-05-21T08:38:03-0300 [applications.mqttapp.BrokerFactory] (TCP Port 5100 Closed)
2020-05-21T08:38:03-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab9552160>
2020-05-21T08:38:03-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-05-21T08:38:03-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab7eb5dd8>
2020-05-21T08:38:03-0300 [SubscriberApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-05-21T08:38:03-0300 [SubscriberApp,client] connection lost - Number of events: 28
2020-05-21T08:38:03-0300 [SubscriberApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-05-21T08:38:03-0300 [SubscriberApp,client] connection lost - Number of events: 29
2020-05-21T08:38:03-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab956d240>
2020-05-21T08:38:03-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9ab956de48>
2020-05-21T08:38:03-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-05-21T08:38:03-0300 [PublisherApp,client] connection lost - Number of events: 30
2020-05-21T08:38:03-0300 [applications.accesspointapp.AccessPointFactory] (TCP Port 8082 Closed)
2020-05-21T08:38:03-0300 [-] Main loop terminated.
