2020-05-16T11:10:14-0300 [-] Creating router ...
2020-05-16T11:10:14-0300 [-] Initializing Router - Number of events: 1
2020-05-16T11:10:15-0300 [-] RouterFactory starting on 8081
2020-05-16T11:10:15-0300 [-] Creating AccessPoint station ...
2020-05-16T11:10:15-0300 [-] Initializing Access Point - Number of events: 2
2020-05-16T11:10:15-0300 [-] AccessPointFactory starting on 8082
2020-05-16T11:10:15-0300 [-] Creating fog node ...
2020-05-16T11:10:15-0300 [-] Initializing Client - Number of events: 3
2020-05-16T11:10:16-0300 [-] Creating fog node ...
2020-05-16T11:10:16-0300 [-] Initializing Client - Number of events: 4
2020-05-16T11:10:16-0300 [-] Creating fog node ...
2020-05-16T11:10:16-0300 [-] Initializing Server - Number of events: 5
2020-05-16T11:10:17-0300 [-] BrokerFactory starting on 5100
2020-05-16T11:10:17-0300 [-] Creating iot node ...
2020-05-16T11:10:17-0300 [-] Initializing Client - Number of events: 6
2020-05-16T11:10:17-0300 [-] Initializing sensor node - Number of events: 7
2020-05-16T11:10:18-0300 [-] Initializing sensor node - Number of events: 8
2020-05-16T11:10:18-0300 [stdout#info] {'14.74 Kwh'}
2020-05-16T11:10:18-0300 [-] Initializing sensor node - Number of events: 9
2020-05-16T11:10:19-0300 [stdout#info] {'12.79 Kwh'}
2020-05-16T11:10:19-0300 [-] Initializing sensor node - Number of events: 10
2020-05-16T11:10:19-0300 [stdout#info] {'14.4 Kwh'}
2020-05-16T11:10:19-0300 [-] Initializing sensor node - Number of events: 11
2020-05-16T11:10:20-0300 [stdout#info] {'10.64 Kwh'}
2020-05-16T11:10:20-0300 [-] Initializing sensor node - Number of events: 12
2020-05-16T11:10:20-0300 [stdout#info] {'3.77 Kwh'}
2020-05-16T11:10:20-0300 [-] Initializing sensor node - Number of events: 13
2020-05-16T11:10:21-0300 [stdout#info] {'22.41 Kwh'}
2020-05-16T11:10:21-0300 [-] Initializing sensor node - Number of events: 14
2020-05-16T11:10:21-0300 [stdout#info] {'13.64 Kwh'}
2020-05-16T11:10:21-0300 [-] Initializing sensor node - Number of events: 15
2020-05-16T11:10:22-0300 [stdout#info] {'15.24 Kwh'}
2020-05-16T11:10:22-0300 [-] Initializing sensor node - Number of events: 16
2020-05-16T11:10:22-0300 [stdout#info] {'5.79 Kwh'}
2020-05-16T11:10:22-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:22-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:22-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:22-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:22-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:22-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:22-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:22-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:22-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:22-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:22-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:22-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:22-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:22-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:22-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:22-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:22-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:22-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:22-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:22-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:22-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:22-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:22-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:22-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:22-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:22-0300 [stdout#info] {'11.47 Kwh'}
2020-05-16T11:10:22-0300 [stdout#info] {'16.01 Kwh'}
2020-05-16T11:10:22-0300 [stdout#info] {'17.7 Kwh'}
2020-05-16T11:10:22-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:10:22-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:10:22-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:10:22-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:10:22-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:10:22-0300 [Uninitialized] 127.0.0.1:46676 - Connected to mqtt broker - Number of events: 17
2020-05-16T11:10:22-0300 [Uninitialized] 127.0.0.1:46676 - sending MQTT SUBSCRIBE REQUEST - Number of events: 18
2020-05-16T11:10:22-0300 [Uninitialized] 127.0.0.1:46678 - Connected to mqtt broker - Number of events: 19
2020-05-16T11:10:22-0300 [Uninitialized] 127.0.0.1:46678 - sending MQTT SUBSCRIBE REQUEST - Number of events: 20
2020-05-16T11:10:22-0300 [Uninitialized] 127.0.0.1:34770 - Connected to mqtt broker - Number of events: 21
2020-05-16T11:10:22-0300 [Uninitialized] 127.0.0.1:34770 - sending MQTT PUBLISH REQUEST - Number of events: 22
2020-05-16T11:10:22-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5d00e978>
2020-05-16T11:10:22-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5d00eb70>
2020-05-16T11:10:22-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5d00eda0>
2020-05-16T11:10:22-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:10:22-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e692828>
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stdout#info] {'20.3 Kwh'}
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stdout#info] {'3.4 Kwh'}
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:23-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:23-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:23-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:23-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:23-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stdout#info] {'5.49 Kwh'}
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stdout#info] {'17.47 Kwh'}
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:24-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:24-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:24-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:24-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:24-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stdout#info] {'21.32 Kwh'}
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stdout#info] {'11.1 Kwh'}
2020-05-16T11:10:25-0300 [stdout#info] {'4.4 Kwh'}
2020-05-16T11:10:25-0300 [stdout#info] {'20.58 Kwh'}
2020-05-16T11:10:25-0300 [stdout#info] {'9.45 Kwh'}
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:25-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:25-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:25-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:25-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:25-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stdout#info] {'4.74 Kwh'}
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stdout#info] {'13.73 Kwh'}
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:26-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:26-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:26-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:26-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:26-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stdout#info] {'9.83 Kwh'}
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stderr#error] Exception in Tkinter callback
2020-05-16T11:10:27-0300 [stderr#error] Traceback (most recent call last):
2020-05-16T11:10:27-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-05-16T11:10:27-0300 [stderr#error]     return self.func(*args)
2020-05-16T11:10:27-0300 [stderr#error] TypeError: update_position_on_screen() takes 1 positional argument but 2 were given
2020-05-16T11:10:27-0300 [stdout#info] {'16.03 Kwh'}
2020-05-16T11:10:27-0300 [-] 127.0.0.1:34770 - sending MQTT PUBLISH REQUEST - Number of events: 23
2020-05-16T11:10:27-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e692358>
2020-05-16T11:10:27-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5d00eda0>
2020-05-16T11:10:27-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:10:27-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e692c88>
2020-05-16T11:10:27-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e692828>
2020-05-16T11:10:28-0300 [stdout#info] {'7.91 Kwh'}
2020-05-16T11:10:28-0300 [stdout#info] {'18.16 Kwh'}
2020-05-16T11:10:28-0300 [stdout#info] {'3.41 Kwh'}
2020-05-16T11:10:28-0300 [stdout#info] {'19.49 Kwh'}
2020-05-16T11:10:28-0300 [stdout#info] {'6.29 Kwh'}
2020-05-16T11:10:29-0300 [stdout#info] {'18.76 Kwh'}
2020-05-16T11:10:29-0300 [stdout#info] {'15.98 Kwh'}
2020-05-16T11:10:30-0300 [stdout#info] {'21.74 Kwh'}
2020-05-16T11:10:30-0300 [stdout#info] {'2.86 Kwh'}
2020-05-16T11:10:31-0300 [stdout#info] {'22.31 Kwh'}
2020-05-16T11:10:31-0300 [stdout#info] {'7.56 Kwh'}
2020-05-16T11:10:31-0300 [stdout#info] {'18.09 Kwh'}
2020-05-16T11:10:31-0300 [stdout#info] {'3.34 Kwh'}
2020-05-16T11:10:31-0300 [stdout#info] {'5.96 Kwh'}
2020-05-16T11:10:32-0300 [stdout#info] {'12.61 Kwh'}
2020-05-16T11:10:32-0300 [stdout#info] {'5.59 Kwh'}
2020-05-16T11:10:32-0300 [-] 127.0.0.1:34770 - sending MQTT PUBLISH REQUEST - Number of events: 24
2020-05-16T11:10:32-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e692ef0>
2020-05-16T11:10:32-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e692358>
2020-05-16T11:10:32-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:10:32-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6ae160>
2020-05-16T11:10:33-0300 [stdout#info] {'22.15 Kwh'}
2020-05-16T11:10:33-0300 [stdout#info] {'21.98 Kwh'}
2020-05-16T11:10:34-0300 [stdout#info] {'8.91 Kwh'}
2020-05-16T11:10:34-0300 [stdout#info] {'8.06 Kwh'}
2020-05-16T11:10:34-0300 [stdout#info] {'8.61 Kwh'}
2020-05-16T11:10:34-0300 [stdout#info] {'13.28 Kwh'}
2020-05-16T11:10:34-0300 [stdout#info] {'17.54 Kwh'}
2020-05-16T11:10:35-0300 [stdout#info] {'10.09 Kwh'}
2020-05-16T11:10:35-0300 [stdout#info] {'17.15 Kwh'}
2020-05-16T11:10:36-0300 [stdout#info] {'9.3 Kwh'}
2020-05-16T11:10:36-0300 [stdout#info] {'4.75 Kwh'}
2020-05-16T11:10:37-0300 [stdout#info] {'10.4 Kwh'}
2020-05-16T11:10:37-0300 [stdout#info] {'3.48 Kwh'}
2020-05-16T11:10:37-0300 [-] 127.0.0.1:34770 - sending MQTT PUBLISH REQUEST - Number of events: 25
2020-05-16T11:10:37-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6ae400>
2020-05-16T11:10:37-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e692ef0>
2020-05-16T11:10:37-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:10:37-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6ae668>
2020-05-16T11:10:37-0300 [stdout#info] {'2.75 Kwh'}
2020-05-16T11:10:37-0300 [stdout#info] {'10.51 Kwh'}
2020-05-16T11:10:37-0300 [stdout#info] {'19.4 Kwh'}
2020-05-16T11:10:38-0300 [stdout#info] {'4.23 Kwh'}
2020-05-16T11:10:38-0300 [stdout#info] {'17.84 Kwh'}
2020-05-16T11:10:39-0300 [stdout#info] {'21.49 Kwh'}
2020-05-16T11:10:39-0300 [stdout#info] {'9.86 Kwh'}
2020-05-16T11:10:40-0300 [stdout#info] {'21.11 Kwh'}
2020-05-16T11:10:40-0300 [stdout#info] {'9.08 Kwh'}
2020-05-16T11:10:40-0300 [stdout#info] {'6.18 Kwh'}
2020-05-16T11:10:40-0300 [stdout#info] {'4.17 Kwh'}
2020-05-16T11:10:40-0300 [stdout#info] {'13.2 Kwh'}
2020-05-16T11:10:41-0300 [stdout#info] {'16.78 Kwh'}
2020-05-16T11:10:41-0300 [stdout#info] {'18.27 Kwh'}
2020-05-16T11:10:42-0300 [stdout#info] {'9.37 Kwh'}
2020-05-16T11:10:42-0300 [stdout#info] {'9.25 Kwh'}
2020-05-16T11:10:42-0300 [-] 127.0.0.1:34770 - sending MQTT PUBLISH REQUEST - Number of events: 26
2020-05-16T11:10:42-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6ae7f0>
2020-05-16T11:10:42-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6ae400>
2020-05-16T11:10:42-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:10:42-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6aeb00>
2020-05-16T11:10:43-0300 [stdout#info] {'16.93 Kwh'}
2020-05-16T11:10:43-0300 [stdout#info] {'3.09 Kwh'}
2020-05-16T11:10:43-0300 [stdout#info] {'7.34 Kwh'}
2020-05-16T11:10:43-0300 [stdout#info] {'11.44 Kwh'}
2020-05-16T11:10:43-0300 [stdout#info] {'7.95 Kwh'}
2020-05-16T11:10:44-0300 [stdout#info] {'21.66 Kwh'}
2020-05-16T11:10:44-0300 [stdout#info] {'22.23 Kwh'}
2020-05-16T11:10:45-0300 [stdout#info] {'15.23 Kwh'}
2020-05-16T11:10:45-0300 [stdout#info] {'8.02 Kwh'}
2020-05-16T11:10:46-0300 [stdout#info] {'11.31 Kwh'}
2020-05-16T11:10:46-0300 [stdout#info] {'18.07 Kwh'}
2020-05-16T11:10:46-0300 [stdout#info] {'7.72 Kwh'}
2020-05-16T11:10:46-0300 [stdout#info] {'14.79 Kwh'}
2020-05-16T11:10:46-0300 [stdout#info] {'7.11 Kwh'}
2020-05-16T11:10:47-0300 [stdout#info] {'14.86 Kwh'}
2020-05-16T11:10:47-0300 [stdout#info] {'8.82 Kwh'}
2020-05-16T11:10:47-0300 [-] 127.0.0.1:34770 - sending MQTT PUBLISH REQUEST - Number of events: 27
2020-05-16T11:10:47-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6aecc0>
2020-05-16T11:10:47-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6ae7f0>
2020-05-16T11:10:47-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:10:47-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6aeeb8>
2020-05-16T11:10:48-0300 [stdout#info] {'13.51 Kwh'}
2020-05-16T11:10:48-0300 [stdout#info] {'9.02 Kwh'}
2020-05-16T11:10:49-0300 [stdout#info] {'15.43 Kwh'}
2020-05-16T11:10:49-0300 [stdout#info] {'21.11 Kwh'}
2020-05-16T11:10:49-0300 [stdout#info] {'13.42 Kwh'}
2020-05-16T11:10:49-0300 [stdout#info] {'4.89 Kwh'}
2020-05-16T11:10:49-0300 [stdout#info] {'6.84 Kwh'}
2020-05-16T11:10:50-0300 [stdout#info] {'20.95 Kwh'}
2020-05-16T11:10:50-0300 [stdout#info] {'21.78 Kwh'}
2020-05-16T11:10:51-0300 [stdout#info] {'8.35 Kwh'}
2020-05-16T11:10:51-0300 [stdout#info] {'4.12 Kwh'}
2020-05-16T11:10:52-0300 [stdout#info] {'3.58 Kwh'}
2020-05-16T11:10:52-0300 [-] 127.0.0.1:34770 - sending MQTT PUBLISH REQUEST - Number of events: 28
2020-05-16T11:10:52-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e64d0f0>
2020-05-16T11:10:52-0300 [stdout#info] {'3.0 Kwh'}
2020-05-16T11:10:52-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6aecc0>
2020-05-16T11:10:52-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:10:52-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e64d2e8>
2020-05-16T11:10:52-0300 [stdout#info] {'5.86 Kwh'}
2020-05-16T11:10:52-0300 [stdout#info] {'6.31 Kwh'}
2020-05-16T11:10:52-0300 [stdout#info] {'14.93 Kwh'}
2020-05-16T11:10:53-0300 [stdout#info] {'22.09 Kwh'}
2020-05-16T11:10:53-0300 [stdout#info] {'3.88 Kwh'}
2020-05-16T11:10:54-0300 [stdout#info] {'5.68 Kwh'}
2020-05-16T11:10:54-0300 [stdout#info] {'20.28 Kwh'}
2020-05-16T11:10:55-0300 [stdout#info] {'17.18 Kwh'}
2020-05-16T11:10:55-0300 [stdout#info] {'11.06 Kwh'}
2020-05-16T11:10:55-0300 [stdout#info] {'19.75 Kwh'}
2020-05-16T11:10:55-0300 [stdout#info] {'10.26 Kwh'}
2020-05-16T11:10:55-0300 [stdout#info] {'2.63 Kwh'}
2020-05-16T11:10:56-0300 [stdout#info] {'7.38 Kwh'}
2020-05-16T11:10:56-0300 [stdout#info] {'14.62 Kwh'}
2020-05-16T11:10:57-0300 [stdout#info] {'14.37 Kwh'}
2020-05-16T11:10:57-0300 [-] 127.0.0.1:34770 - sending MQTT PUBLISH REQUEST - Number of events: 29
2020-05-16T11:10:57-0300 [stdout#info] {'22.27 Kwh'}
2020-05-16T11:10:57-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e64d470>
2020-05-16T11:10:57-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e64d0f0>
2020-05-16T11:10:57-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:10:57-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e64d748>
2020-05-16T11:10:58-0300 [stdout#info] {'7.56 Kwh'}
2020-05-16T11:10:58-0300 [stdout#info] {'19.56 Kwh'}
2020-05-16T11:10:58-0300 [stdout#info] {'14.5 Kwh'}
2020-05-16T11:10:58-0300 [stdout#info] {'18.0 Kwh'}
2020-05-16T11:10:58-0300 [stdout#info] {'3.42 Kwh'}
2020-05-16T11:10:59-0300 [stdout#info] {'12.21 Kwh'}
2020-05-16T11:10:59-0300 [stdout#info] {'17.75 Kwh'}
2020-05-16T11:11:00-0300 [stdout#info] {'17.64 Kwh'}
2020-05-16T11:11:00-0300 [stdout#info] {'18.36 Kwh'}
2020-05-16T11:11:01-0300 [stdout#info] {'5.68 Kwh'}
2020-05-16T11:11:01-0300 [stdout#info] {'18.37 Kwh'}
2020-05-16T11:11:01-0300 [stdout#info] {'11.03 Kwh'}
2020-05-16T11:11:01-0300 [stdout#info] {'2.91 Kwh'}
2020-05-16T11:11:01-0300 [stdout#info] {'18.69 Kwh'}
2020-05-16T11:11:02-0300 [stdout#info] {'8.18 Kwh'}
2020-05-16T11:11:02-0300 [stdout#info] {'14.65 Kwh'}
2020-05-16T11:11:02-0300 [-] 127.0.0.1:34770 - sending MQTT PUBLISH REQUEST - Number of events: 30
2020-05-16T11:11:02-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e64d8d0>
2020-05-16T11:11:02-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e64d470>
2020-05-16T11:11:02-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:11:02-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e64dba8>
2020-05-16T11:11:03-0300 [stdout#info] {'11.57 Kwh'}
2020-05-16T11:11:03-0300 [stdout#info] {'10.58 Kwh'}
2020-05-16T11:11:04-0300 [stdout#info] {'16.47 Kwh'}
2020-05-16T11:11:04-0300 [stdout#info] {'18.06 Kwh'}
2020-05-16T11:11:04-0300 [stdout#info] {'12.9 Kwh'}
2020-05-16T11:11:04-0300 [stdout#info] {'5.08 Kwh'}
2020-05-16T11:11:04-0300 [stdout#info] {'5.96 Kwh'}
2020-05-16T11:11:05-0300 [stdout#info] {'12.39 Kwh'}
2020-05-16T11:11:05-0300 [stdout#info] {'15.85 Kwh'}
2020-05-16T11:11:06-0300 [stdout#info] {'19.44 Kwh'}
2020-05-16T11:11:06-0300 [stdout#info] {'20.55 Kwh'}
2020-05-16T11:11:07-0300 [stdout#info] {'10.85 Kwh'}
2020-05-16T11:11:07-0300 [stdout#info] {'21.23 Kwh'}
2020-05-16T11:11:07-0300 [-] 127.0.0.1:34770 - sending MQTT PUBLISH REQUEST - Number of events: 31
2020-05-16T11:11:07-0300 [stdout#info] {'20.62 Kwh'}
2020-05-16T11:11:07-0300 [stdout#info] {'11.12 Kwh'}
2020-05-16T11:11:07-0300 [stdout#info] {'10.86 Kwh'}
2020-05-16T11:11:07-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e64dd30>
2020-05-16T11:11:07-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e64d8d0>
2020-05-16T11:11:07-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:11:07-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e671048>
2020-05-16T11:11:08-0300 [stdout#info] {'8.13 Kwh'}
2020-05-16T11:11:08-0300 [stdout#info] {'4.72 Kwh'}
2020-05-16T11:11:09-0300 [stdout#info] {'5.02 Kwh'}
2020-05-16T11:11:09-0300 [stdout#info] {'7.26 Kwh'}
2020-05-16T11:11:10-0300 [stdout#info] {'14.93 Kwh'}
2020-05-16T11:11:10-0300 [stdout#info] {'12.21 Kwh'}
2020-05-16T11:11:10-0300 [stdout#info] {'14.22 Kwh'}
2020-05-16T11:11:10-0300 [stdout#info] {'15.9 Kwh'}
2020-05-16T11:11:10-0300 [stdout#info] {'10.59 Kwh'}
2020-05-16T11:11:11-0300 [stdout#info] {'21.51 Kwh'}
2020-05-16T11:11:11-0300 [stdout#info] {'4.78 Kwh'}
2020-05-16T11:11:12-0300 [stdout#info] {'15.55 Kwh'}
2020-05-16T11:11:12-0300 [-] 127.0.0.1:34770 - sending MQTT PUBLISH REQUEST - Number of events: 32
2020-05-16T11:11:12-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e671160>
2020-05-16T11:11:12-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e64dd30>
2020-05-16T11:11:12-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:11:12-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6714a8>
2020-05-16T11:11:12-0300 [stdout#info] {'11.63 Kwh'}
2020-05-16T11:11:13-0300 [stdout#info] {'9.95 Kwh'}
2020-05-16T11:11:13-0300 [stdout#info] {'21.43 Kwh'}
2020-05-16T11:11:13-0300 [stdout#info] {'18.88 Kwh'}
2020-05-16T11:11:13-0300 [stdout#info] {'17.24 Kwh'}
2020-05-16T11:11:13-0300 [stdout#info] {'5.47 Kwh'}
2020-05-16T11:11:14-0300 [stdout#info] {'6.01 Kwh'}
2020-05-16T11:11:14-0300 [stdout#info] {'5.79 Kwh'}
2020-05-16T11:11:15-0300 [stdout#info] {'16.86 Kwh'}
2020-05-16T11:11:15-0300 [stdout#info] {'20.89 Kwh'}
2020-05-16T11:11:16-0300 [stdout#info] {'8.99 Kwh'}
2020-05-16T11:11:16-0300 [stdout#info] {'3.48 Kwh'}
2020-05-16T11:11:16-0300 [stdout#info] {'21.23 Kwh'}
2020-05-16T11:11:16-0300 [stdout#info] {'6.44 Kwh'}
2020-05-16T11:11:16-0300 [stdout#info] {'9.04 Kwh'}
2020-05-16T11:11:17-0300 [stdout#info] {'12.27 Kwh'}
2020-05-16T11:11:17-0300 [stdout#info] {'13.45 Kwh'}
2020-05-16T11:11:17-0300 [-] 127.0.0.1:34770 - sending MQTT PUBLISH REQUEST - Number of events: 33
2020-05-16T11:11:17-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e671630>
2020-05-16T11:11:17-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e671160>
2020-05-16T11:11:17-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:11:17-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e671908>
2020-05-16T11:11:18-0300 [stdout#info] {'20.03 Kwh'}
2020-05-16T11:11:18-0300 [stdout#info] {'6.53 Kwh'}
2020-05-16T11:11:19-0300 [stdout#info] {'10.68 Kwh'}
2020-05-16T11:11:19-0300 [stdout#info] {'11.26 Kwh'}
2020-05-16T11:11:19-0300 [stdout#info] {'14.14 Kwh'}
2020-05-16T11:11:19-0300 [stdout#info] {'19.33 Kwh'}
2020-05-16T11:11:19-0300 [stdout#info] {'18.54 Kwh'}
2020-05-16T11:11:20-0300 [stdout#info] {'8.5 Kwh'}
2020-05-16T11:11:20-0300 [stdout#info] {'11.34 Kwh'}
2020-05-16T11:11:21-0300 [stdout#info] {'4.19 Kwh'}
2020-05-16T11:11:21-0300 [stdout#info] {'9.23 Kwh'}
2020-05-16T11:11:22-0300 [stdout#info] {'15.41 Kwh'}
2020-05-16T11:11:22-0300 [stdout#info] {'21.51 Kwh'}
2020-05-16T11:11:22-0300 [-] 127.0.0.1:34770 - sending MQTT PUBLISH REQUEST - Number of events: 34
2020-05-16T11:11:22-0300 [stdout#info] {'18.77 Kwh'}
2020-05-16T11:11:22-0300 [stdout#info] {'9.2 Kwh'}
2020-05-16T11:11:22-0300 [stdout#info] {'14.22 Kwh'}
2020-05-16T11:11:22-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e671a90>
2020-05-16T11:11:22-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e671630>
2020-05-16T11:11:22-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:11:22-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e671d68>
2020-05-16T11:11:23-0300 [stdout#info] {'8.19 Kwh'}
2020-05-16T11:11:23-0300 [stdout#info] {'3.18 Kwh'}
2020-05-16T11:11:24-0300 [stdout#info] {'18.42 Kwh'}
2020-05-16T11:11:24-0300 [stdout#info] {'14.83 Kwh'}
2020-05-16T11:11:25-0300 [stdout#info] {'5.19 Kwh'}
2020-05-16T11:11:25-0300 [stdout#info] {'3.04 Kwh'}
2020-05-16T11:11:25-0300 [stdout#info] {'5.96 Kwh'}
2020-05-16T11:11:25-0300 [stdout#info] {'12.48 Kwh'}
2020-05-16T11:11:25-0300 [stdout#info] {'16.49 Kwh'}
2020-05-16T11:11:26-0300 [stdout#info] {'10.21 Kwh'}
2020-05-16T11:11:26-0300 [stdout#info] {'5.79 Kwh'}
2020-05-16T11:11:27-0300 [stdout#info] {'9.66 Kwh'}
2020-05-16T11:11:27-0300 [-] 127.0.0.1:34770 - sending MQTT PUBLISH REQUEST - Number of events: 35
2020-05-16T11:11:27-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e671ef0>
2020-05-16T11:11:27-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e671a90>
2020-05-16T11:11:27-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:11:27-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5cfb5208>
2020-05-16T11:11:27-0300 [stdout#info] {'17.01 Kwh'}
2020-05-16T11:11:28-0300 [stdout#info] {'2.57 Kwh'}
2020-05-16T11:11:28-0300 [stdout#info] {'21.91 Kwh'}
2020-05-16T11:11:28-0300 [stdout#info] {'17.66 Kwh'}
2020-05-16T11:11:28-0300 [stdout#info] {'21.77 Kwh'}
2020-05-16T11:11:28-0300 [stdout#info] {'13.62 Kwh'}
2020-05-16T11:11:29-0300 [stdout#info] {'4.54 Kwh'}
2020-05-16T11:11:29-0300 [stdout#info] {'12.69 Kwh'}
2020-05-16T11:11:30-0300 [stdout#info] {'15.0 Kwh'}
2020-05-16T11:11:30-0300 [stdout#info] {'10.25 Kwh'}
2020-05-16T11:11:31-0300 [stdout#info] {'3.96 Kwh'}
2020-05-16T11:11:31-0300 [stdout#info] {'5.16 Kwh'}
2020-05-16T11:11:31-0300 [stdout#info] {'12.96 Kwh'}
2020-05-16T11:11:31-0300 [stdout#info] {'21.14 Kwh'}
2020-05-16T11:11:31-0300 [stdout#info] {'6.53 Kwh'}
2020-05-16T11:11:32-0300 [stdout#info] {'19.36 Kwh'}
2020-05-16T11:11:32-0300 [stdout#info] {'4.45 Kwh'}
2020-05-16T11:11:32-0300 [-] 127.0.0.1:34770 - sending MQTT PUBLISH REQUEST - Number of events: 36
2020-05-16T11:11:32-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5cfb5390>
2020-05-16T11:11:32-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e671ef0>
2020-05-16T11:11:32-0300 [stdout#info] This divice have no simulation core instance
2020-05-16T11:11:32-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5cfb5668>
2020-05-16T11:11:33-0300 [stdout#info] {'11.27 Kwh'}
2020-05-16T11:11:33-0300 [stdout#info] {'6.98 Kwh'}
2020-05-16T11:11:34-0300 [stdout#info] {'16.27 Kwh'}
2020-05-16T11:11:34-0300 [stdout#info] {'5.37 Kwh'}
2020-05-16T11:11:34-0300 [stdout#info] {'6.06 Kwh'}
2020-05-16T11:11:34-0300 [stdout#info] {'19.19 Kwh'}
2020-05-16T11:11:34-0300 [stdout#info] {'14.94 Kwh'}
2020-05-16T11:11:34-0300 [-] Received SIGINT, shutting down.
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e64d748>
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e671048>
2020-05-16T11:11:34-0300 [applications.mqttapp.BrokerFactory] (TCP Port 5100 Closed)
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e671908>
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6ae160>
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5d00e978>
2020-05-16T11:11:34-0300 [SubscriberApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-05-16T11:11:34-0300 [SubscriberApp,client] connection lost - Number of events: 37
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5cfb5208>
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e64d2e8>
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6aeb00>
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5d00eb70>
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e64dba8>
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5cfb5390>
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e692c88>
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6714a8>
2020-05-16T11:11:34-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e671d68>
2020-05-16T11:11:34-0300 [SubscriberApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-05-16T11:11:34-0300 [SubscriberApp,client] connection lost - Number of events: 38
2020-05-16T11:11:34-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-05-16T11:11:34-0300 [PublisherApp,client] connection lost - Number of events: 39
2020-05-16T11:11:34-0300 [applications.accesspointapp.AccessPointFactory] (TCP Port 8082 Closed)
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6ae668>
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5cfb5668>
2020-05-16T11:11:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f6e5e6aeeb8>
2020-05-16T11:11:34-0300 [-] Main loop terminated.
